-- update 24

-- fix SC esc destination
insert into getback values (0, 0, 0, 0, 304, 32857, 32898, 32857, 32898, 32857, 32898, 304, 0, 0, 0, 1, 'Silent Cavern');

-- fix name on lump of iron and heart of firebird
update etcitem set name = 'Lump of Iron' where item_id = 40408;
update etcitem set name = 'Heart of Firebird' where item_id = 40409;

-- disable 55+ DE polys (reenable these after ep6/u merge)
-- ancient black assassin morph (polyid: 5727)
update polymorphs set minlevel = 99 where id = 5727;
-- ancient silver assassin morph (polyid: 5730)
update polymorphs set minlevel = 99 where id = 5730;
-- ancient gold assassin morph (polyid: 5733)
update polymorphs set minlevel = 99 where id = 5733;
-- ancient platinum assassin morph (polyid: 5736)
update polymorphs set minlevel = 99 where id = 5736;

-- disable red orc poly (crashes ep5 clients)
update polymorphs set minlevel = 99 where id = 6010;

-- make earth boss rock skill do AoE damage
update skills set area = 3 where skill_id = 10020;

-- remove invalid items in shop table
delete from shop where item_id in (0, 210001, 210002, 210003, 210004, 210005, 210006);

-- create element families for elemental grave mops
update npc set family = 'spiritearth' where npcid in (45416, 45508, 45592);
update npc set family = 'spiritwind' where npcid in (45418, 45418, 45593);
update npc set family = 'spiritwater' where npcid in (45419, 45500, 45591);
update npc set family = 'spiritfire' where npcid in (45424, 45511, 45594);
update npc set family = '' where npcid in (45501, 45502, 45535, 45646);

-- activate additional elemental grave spawn
-- fangs
update spawnlist set count = 1 where id in (17648, 17654, 17660, 17666, 17672, 17678, 17684, 17690, 17696, 17702, 17726, 17732);
-- masters
update spawnlist set count = 1 where id in (20126, 20712, 20742, 20750);
-- undead
update spawnlist set count = 1 where id in (20132, 20138, 20144, 20150, 20156, 20162, 20168, 23442);

-- create elekkadom skill
insert into skills values (11000, 'Elekkadom Electrical Charge', 0, 0, 8, 0, 0, 0, 0, 0, 'attack', 3, 50, 5, 5, 0, 0, 2, 64, 0, 2, 0, 0, 0, '', 1714, 0, 0, 0, 0);

-- set elekkadoms to use mobskill
insert into mobskill values (45279, 0, 'Elekkadom', 2, 25, 0, 0, -1, 0, 0, 0, 0, 0, 8, 11000, 1714, 0, 0, 0, 0, 0);
insert into mobskill values (45819, 0, 'Elekkadom', 2, 25, 0, 0, -1, 0, 0, 0, 0, 0, 8, 11000, 1714, 0, 0, 0, 0, 0);
insert into mobskill values (45487, 0, 'Subterranean Elekkadom', 2, 30, 0, 0, -1, 0, 0, 0, 0, 0, 16, 11000, 1714, 0, 0, 0, 0, 0);
insert into mobskill values (45732, 0, 'Grave Elekkadom', 2, 30, 0, 0, -1, 0, 0, 0, 0, 0, 16, 11000, 1714, 0, 0, 0, 0, 0);

-- add toi81f to knight vald droplist
insert into droplist values (45618, 40111, 1, 5, 500000);

-- fix all prince spells
-- Glowing Aura
update skills set name = 'Glowing Aura', skill_level = '15',  skill_number = '1',  mpConsume = '30',   hpConsume = '0',  
itemConsumeId = '0',   itemConsumeCount = '0', reuseDelay =  '0', buffDuration = '640', target = 'none',  target_to = '8',  
damage_value = '0', damage_dice = '0', damage_dice_count = '0', probability_value = '0',  probability_dice = '0', 
attr = '0',  type = '2',  lawful =  '0', ranged = '0', area = '-1', through = '0',  id = '2', nameid = '$1996', castgfx = '2277', 
sysmsgID_happen = '0',  sysmsgID_stop = '0', sysmsgID_fail = '0',  arrowType = '0' 
where skill_id = 114;
update skills set name = 'CallPledgeMember', skill_level =  '15', skill_number = '3',  mpConsume = '40',  hpConsume = '0', 
itemConsumeId = '0',  itemConsumeCount = '0', reuseDelay = '0',  buffDuration = '0',  target = 'buff',  target_to = '0',  
damage_value = '0', damage_dice =  '0', damage_dice_count =  '0', probability_value = '0',  probability_dice = '0', 
attr = '0',  type = '2', lawful = '0', ranged = '0', area = '-1', through =  '0', id = '8', nameid = '$1977', castgfx = '0', 
sysmsgID_happen = '0', sysmsgID_stop = '0', sysmsgID_fail = '0', arrowType = '0' 
where skill_id = 116;
update skills set name = 'Shining Aura', skill_level = '15',skill_number = '2', mpConsume = '30', hpConsume = '0',
itemConsumeId = '0', itemConsumeCount = '0', reuseDelay = '0', buffDuration = '640', target = 'none', target_to = '8', 
damage_value = '0', damage_dice = '0', damage_dice_count = '0', probability_value = '0', probability_dice = '0', 
attr = '0', type = '2', lawful = '0', ranged = '0', area = '-1', through = '0', id = '4', nameid = '', castgfx = '3941', 
sysmsgID_happen = '0', sysmsgID_stop = '0', sysmsgID_fail = '280', arrowType = '0' 
where skill_id = 115;
update skills set name = 'Brave Aura', skill_level = '15', skill_number = '4', mpConsume = '40',  hpConsume = '0',
itemConsumeId = '0', itemConsumeCount = '0', reuseDelay = '0', buffDuration = '640', target = 'none', target_to = '8', 
damage_value = '0', damage_dice = '0', damage_dice_count = '0', probability_value = '0', probability_dice =  '0', 
attr = '0', type = '2', lawful =  '0', ranged = '0', area = '-1', through = '0', id = '16', nameid = '$3178', castgfx = '3942', 
sysmsgID_happen = '0', sysmsgID_stop = '0', sysmsgID_fail = '0', arrowType = '0' 
where skill_id = 117;
update skills set name = 'Teleport to Pledge Member', skill_level = '15', skill_number = '5', mpConsume = '30', hpConsume = '0', 
itemConsumeId = '0', itemConsumeCount = '0', reuseDelay = '0', buffDuration = '0', target = 'buff', target_to = '0', 
damage_value = '0', damage_dice = '0', damage_dice_count = '0', probability_value = '0', probability_dice =  '0', 
attr = '0', type = '2', lawful =  '0', ranged = '0', area = '-1', through = '0', id = '32', nameid = '', castgfx = '0', 
sysmsgID_happen = '0', sysmsgID_stop = '0', sysmsgID_fail = '280', arrowType = '0' 
where skill_id = 118;

-- all tribal orcs should be aggro to sosc
update npc set agrososc = 1 where npcid = 45171;

-- remove tamable from orc wizards to prevent killing shopmode chars with aoe
update npc set tamable = 0 where npcid = 45121;

-- slightly reduce sema's magic damage to be more in line with the other members of caspa group
update mobskill set leverage = 35 where mobid = 45464 and actno = 0;

-- correct misnamed pan's mane/fairydust
update etcitem set name = 'Pan\'s Mane' where item_id = 40520;
update etcitem set name = 'Fairydust' where item_id = 40520;

-- fix fire arrow and stalac
update skills set name = 'FireArrow', skill_number = 6, attr = 2, id = 64, nameid = '$1969', castgfx = 1583, arrowType = 1 where skill_id = 15;
update skills set name = 'Stalac', skill_number = 7, attr = 1, id = 128, nameid = '$1968', castgfx = 1801, arrowType = 0 where skill_id = 16;

-- increase hp/mp regen interval of tiger/battle tiger
update npc set hprinterval = 2500 where npcid = 45313;
update npc set hprinterval = 2500, mprinterval = 2500 where npcid = 45710;

-- increase hp regen interval of greater elf summons, and add mp regen
update npc set hprinterval = 2500, mprinterval = 2500, mpr = 5 where npcid in (81050, 81051, 81052, 81053);

-- add mobskills for greater elf summons
insert into mobskill values (81050, 0, 'Summoned Spirit of Fire', 2, 100, 0, 0, -6, 0, 0, 0, 0, 0, 3, 15, 1801, 0, 0, 0, 0, 0); 
insert into mobskill values (81051, 0, 'Summoned Spirit of Water', 2, 100, 0, 0, -6, 0, 0, 0, 0, 0, 3, 6, 1797, 0, 0, 0, 0, 0); 
insert into mobskill values (81052, 0, 'Summoned Spirit of Wind', 2, 100, 0, 0, -6, 0, 0, 0, 0, 0, 3, 7, 1799, 0, 0, 0, 0, 0); 
insert into mobskill values (81053, 0, 'Summoned Spirit of Earth', 2, 100, 0, 0, -6, 0, 0, 0, 0, 0, 3, 16, 1583, 0, 0, 0, 0, 0); 

-- activate skt drist spawn
update spawnlist_npc set count = 1 where npc_templateid = 50055;

-- fix all mapids names
update mapids set locationname = 'Talking Island' where mapid = 0;
update mapids set locationname = 'Talking Island Caves 1F' where mapid = 1;
update mapids set locationname = 'Talking Island Caves 2F' where mapid = 2;
update mapids set locationname = 'Gunter\'s Cave' where mapid = 3;
update mapids set locationname = 'Mainland Aden' where mapid = 4;
update mapids set locationname = 'Main Land Caves 1F' where mapid = 7;
update mapids set locationname = 'Main Land Caves 2F' where mapid = 8;
update mapids set locationname = 'Main Land Caves 3F' where mapid = 9;
update mapids set locationname = 'Main Land Caves 4F' where mapid = 10;
update mapids set locationname = 'Main Land Caves 5F' where mapid = 11;
update mapids set locationname = 'Main Land Caves 6F' where mapid = 12;
update mapids set locationname = 'Main Land Caves 7F' where mapid = 13;
update mapids set locationname = 'Underground Passage' where mapid = 14;
update mapids set locationname = 'Kent Castle' where mapid = 15;
update mapids set locationname = 'Nerupa\'s Cave' where mapid = 17;
update mapids set locationname = 'Elven Dungeon 1F' where mapid = 19;
update mapids set locationname = 'Elven Dungeon 2F' where mapid = 20;
update mapids set locationname = 'Elven Dungeon 3F' where mapid = 21;
update mapids set locationname = 'Windawood Castle Dungeon 1F' where mapid = 23;
update mapids set locationname = 'Windawood Castle Dungeon 2F' where mapid = 24;
update mapids set locationname = 'Silver Knight Town Caves 1F' where mapid = 25;
update mapids set locationname = 'Silver Knight Town Caves 2F' where mapid = 26;
update mapids set locationname = 'Silver Knight Town Caves 3F' where mapid = 27;
update mapids set locationname = 'Silver Knight Town Caves 4F' where mapid = 28;
update mapids set locationname = 'Windawood Inner Castle' where mapid = 29;
update mapids set locationname = 'Dragon Valley Caves 1F' where mapid = 30;
update mapids set locationname = 'Dragon Valley Caves 2F' where mapid = 31;
update mapids set locationname = 'Dragon Valley Caves 3F' where mapid = 32;
update mapids set locationname = 'Dragon Valley Caves 4F' where mapid = 33;
update mapids set locationname = 'Dragon Valley Caves 5F' where mapid = 35;
update mapids set locationname = 'Dragon Valley Caves 6F' where mapid = 36;
update mapids set locationname = 'Dragon Valley Caves 7F' where mapid = 37;
update mapids set locationname = 'Ant Caves 1F' where mapid = 43;
update mapids set locationname = 'Ant Caves 2F' where mapid = 44;
update mapids set locationname = 'Ant Caves 3F' where mapid = 45;
update mapids set locationname = 'Ant Caves 4F' where mapid = 46;
update mapids set locationname = 'Ant Caves 5F' where mapid = 47;
update mapids set locationname = 'Ant Caves 6F' where mapid = 48;
update mapids set locationname = 'Ant Caves 7F' where mapid = 49;
update mapids set locationname = 'Ant Caves 8F' where mapid = 50;
update mapids set locationname = 'Ant Caves 9F' where mapid = 51;
update mapids set locationname = 'Giran Castle' where mapid = 52;
update mapids set locationname = 'Giran Dungeon 1F' where mapid = 53;
update mapids set locationname = 'Giran Dungeon 2F' where mapid = 54;
update mapids set locationname = 'Giran Dungeon 3F' where mapid = 55;
update mapids set locationname = 'Giran Dungeon 4F' where mapid = 56;
update mapids set locationname = 'Singing Island' where mapid = 57;
update mapids set locationname = 'Hidden Valley' where mapid = 58;
update mapids set locationname = 'Heine Dungeon 1F' where mapid = 59;
update mapids set locationname = 'Heine Dungeon 2F' where mapid = 60;
update mapids set locationname = 'Heine Dungeon 3F' where mapid = 61;
update mapids set locationname = 'Sanctuary of Eva' where mapid = 62;
update mapids set locationname = 'Kingdom of Eva' where mapid = 63;
update mapids set locationname = 'Heine Inner Castle' where mapid = 64;
update mapids set locationname = 'Lair of Fafurion' where mapid = 65;
update mapids set locationname = 'Iron Gate Guild Inner Castle' where mapid = 66;
update mapids set locationname = 'Lair of Valakas' where mapid = 67;
update mapids set locationname = 'Singing Island' where mapid = 68;
update mapids set locationname = 'Hidden Valley' where mapid = 69;
update mapids set locationname = 'Forgotten Island' where mapid = 70;
update mapids set locationname = 'Crystal Cavern 1F' where mapid = 72;
update mapids set locationname = 'Crystal Cavern 2F' where mapid = 73;
update mapids set locationname = 'Crystal Cavern 3F' where mapid = 74;
update mapids set locationname = 'Ivory Tower 1F' where mapid = 75;
update mapids set locationname = 'Ivory Tower 2F' where mapid = 76;
update mapids set locationname = 'Ivory Tower 3F' where mapid = 77;
update mapids set locationname = 'Ivory Tower 4F' where mapid = 78;
update mapids set locationname = 'Ivory Tower 5F' where mapid = 79;
update mapids set locationname = 'Ivory Tower 6F' where mapid = 80;
update mapids set locationname = 'Ivory Tower 7F' where mapid = 81;
update mapids set locationname = 'Ivory Tower 8F' where mapid = 82;
update mapids set locationname = 'Singing Island Dungeon' where mapid = 85;
update mapids set locationname = 'Hidden Valley Dungeon' where mapid = 86;
update mapids set locationname = 'Tower of Insolence 1F' where mapid = 101;
update mapids set locationname = 'Tower of Insolence 2F' where mapid = 102;
update mapids set locationname = 'Tower of Insolence 3F' where mapid = 103;
update mapids set locationname = 'Tower of Insolence 4F' where mapid = 104;
update mapids set locationname = 'Tower of Insolence 5F' where mapid = 105;
update mapids set locationname = 'Tower of Insolence 6F' where mapid = 106;
update mapids set locationname = 'Tower of Insolence 7F' where mapid = 107;
update mapids set locationname = 'Tower of Insolence 8F' where mapid = 108;
update mapids set locationname = 'Tower of Insolence 9F' where mapid = 109;
update mapids set locationname = 'Tower of Insolence 10F' where mapid = 110;
update mapids set locationname = 'Tower of Insolence 11F' where mapid = 111;
update mapids set locationname = 'Tower of Insolence 12F' where mapid = 112;
update mapids set locationname = 'Tower of Insolence 13F' where mapid = 113;
update mapids set locationname = 'Tower of Insolence 14F' where mapid = 114;
update mapids set locationname = 'Tower of Insolence 15F' where mapid = 115;
update mapids set locationname = 'Tower of Insolence 16F' where mapid = 116;
update mapids set locationname = 'Tower of Insolence 17F' where mapid = 117;
update mapids set locationname = 'Tower of Insolence 18F' where mapid = 118;
update mapids set locationname = 'Tower of Insolence 19F' where mapid = 119;
update mapids set locationname = 'Tower of Insolence 20F' where mapid = 120;
update mapids set locationname = 'Tower of Insolence 21F' where mapid = 121;
update mapids set locationname = 'Tower of Insolence 22F' where mapid = 122;
update mapids set locationname = 'Tower of Insolence 23F' where mapid = 123;
update mapids set locationname = 'Tower of Insolence 24F' where mapid = 124;
update mapids set locationname = 'Tower of Insolence 25F' where mapid = 125;
update mapids set locationname = 'Tower of Insolence 26F' where mapid = 126;
update mapids set locationname = 'Tower of Insolence 27F' where mapid = 127;
update mapids set locationname = 'Tower of Insolence 28F' where mapid = 128;
update mapids set locationname = 'Tower of Insolence 29F' where mapid = 129;
update mapids set locationname = 'Tower of Insolence 30F' where mapid = 130;
update mapids set locationname = 'Tower of Insolence 31F' where mapid = 131;
update mapids set locationname = 'Tower of Insolence 32F' where mapid = 132;
update mapids set locationname = 'Tower of Insolence 33F' where mapid = 133;
update mapids set locationname = 'Tower of Insolence 34F' where mapid = 134;
update mapids set locationname = 'Tower of Insolence 35F' where mapid = 135;
update mapids set locationname = 'Tower of Insolence 36F' where mapid = 136;
update mapids set locationname = 'Tower of Insolence 37F' where mapid = 137;
update mapids set locationname = 'Tower of Insolence 38F' where mapid = 138;
update mapids set locationname = 'Tower of Insolence 39F' where mapid = 139;
update mapids set locationname = 'Tower of Insolence 40F' where mapid = 140;
update mapids set locationname = 'Tower of Insolence 41F' where mapid = 141;
update mapids set locationname = 'Tower of Insolence 42F' where mapid = 142;
update mapids set locationname = 'Tower of Insolence 43F' where mapid = 143;
update mapids set locationname = 'Tower of Insolence 44F' where mapid = 144;
update mapids set locationname = 'Tower of Insolence 45F' where mapid = 145;
update mapids set locationname = 'Tower of Insolence 46F' where mapid = 146;
update mapids set locationname = 'Tower of Insolence 47F' where mapid = 147;
update mapids set locationname = 'Tower of Insolence 48F' where mapid = 148;
update mapids set locationname = 'Tower of Insolence 49F' where mapid = 149;
update mapids set locationname = 'Tower of Insolence 50F' where mapid = 150;
update mapids set locationname = 'Tower of Insolence 51F' where mapid = 151;
update mapids set locationname = 'Tower of Insolence 52F' where mapid = 152;
update mapids set locationname = 'Tower of Insolence 53F' where mapid = 153;
update mapids set locationname = 'Tower of Insolence 54F' where mapid = 154;
update mapids set locationname = 'Tower of Insolence 55F' where mapid = 155;
update mapids set locationname = 'Tower of Insolence 56F' where mapid = 156;
update mapids set locationname = 'Tower of Insolence 57F' where mapid = 157;
update mapids set locationname = 'Tower of Insolence 58F' where mapid = 158;
update mapids set locationname = 'Tower of Insolence 59F' where mapid = 159;
update mapids set locationname = 'Tower of Insolence 60F' where mapid = 160;
update mapids set locationname = 'Tower of Insolence 61F' where mapid = 161;
update mapids set locationname = 'Tower of Insolence 62F' where mapid = 162;
update mapids set locationname = 'Tower of Insolence 63F' where mapid = 163;
update mapids set locationname = 'Tower of Insolence 64F' where mapid = 164;
update mapids set locationname = 'Tower of Insolence 65F' where mapid = 165;
update mapids set locationname = 'Tower of Insolence 66F' where mapid = 166;
update mapids set locationname = 'Tower of Insolence 67F' where mapid = 167;
update mapids set locationname = 'Tower of Insolence 68F' where mapid = 168;
update mapids set locationname = 'Tower of Insolence 69F' where mapid = 169;
update mapids set locationname = 'Tower of Insolence 70F' where mapid = 170;
update mapids set locationname = 'Tower of Insolence 71F' where mapid = 171;
update mapids set locationname = 'Tower of Insolence 72F' where mapid = 172;
update mapids set locationname = 'Tower of Insolence 73F' where mapid = 173;
update mapids set locationname = 'Tower of Insolence 74F' where mapid = 174;
update mapids set locationname = 'Tower of Insolence 75F' where mapid = 175;
update mapids set locationname = 'Tower of Insolence 76F' where mapid = 176;
update mapids set locationname = 'Tower of Insolence 77F' where mapid = 177;
update mapids set locationname = 'Tower of Insolence 78F' where mapid = 178;
update mapids set locationname = 'Tower of Insolence 79F' where mapid = 179;
update mapids set locationname = 'Tower of Insolence 80F' where mapid = 180;
update mapids set locationname = 'Tower of Insolence 81F' where mapid = 181;
update mapids set locationname = 'Tower of Insolence 82F' where mapid = 182;
update mapids set locationname = 'Tower of Insolence 83F' where mapid = 183;
update mapids set locationname = 'Tower of Insolence 84F' where mapid = 184;
update mapids set locationname = 'Tower of Insolence 85F' where mapid = 185;
update mapids set locationname = 'Tower of Insolence 86F' where mapid = 186;
update mapids set locationname = 'Tower of Insolence 87F' where mapid = 187;
update mapids set locationname = 'Tower of Insolence 88F' where mapid = 188;
update mapids set locationname = 'Tower of Insolence 89F' where mapid = 189;
update mapids set locationname = 'Tower of Insolence 90F' where mapid = 190;
update mapids set locationname = 'Tower of Insolence 91F' where mapid = 191;
update mapids set locationname = 'Tower of Insolence 92F' where mapid = 192;
update mapids set locationname = 'Tower of Insolence 93F' where mapid = 193;
update mapids set locationname = 'Tower of Insolence 94F' where mapid = 194;
update mapids set locationname = 'Tower of Insolence 95F' where mapid = 195;
update mapids set locationname = 'Tower of Insolence 96F' where mapid = 196;
update mapids set locationname = 'Tower of Insolence 97F' where mapid = 197;
update mapids set locationname = 'Tower of Insolence 98F' where mapid = 198;
update mapids set locationname = 'Tower of Insolence 99F' where mapid = 199;
update mapids set locationname = 'Tower of Insolence 100F' where mapid = 200;
update mapids set locationname = 'Kent Castle Dungeon 1F' where mapid = 240;
update mapids set locationname = 'Kent Castle Dungeon 2F' where mapid = 241;
update mapids set locationname = 'Kent Castle Dungeon 3F' where mapid = 242;
update mapids set locationname = 'Kent Castle Dungeon 4F' where mapid = 243;
update mapids set locationname = 'Blessed land of tainted' where mapid = 244;
update mapids set locationname = 'Unknown Castle 1F' where mapid = 248;
update mapids set locationname = 'Unknown Castle 2F' where mapid = 249;
update mapids set locationname = 'Unknown Castle 3F' where mapid = 250;
update mapids set locationname = 'Unknown' where mapid = 251;
update mapids set locationname = 'Unknown 1F' where mapid = 252;
update mapids set locationname = 'Unknown 2F' where mapid = 253;
update mapids set locationname = 'Unknown 3F' where mapid = 254;
update mapids set locationname = 'Unknown 1F' where mapid = 255;
update mapids set locationname = 'Unknown 2F' where mapid = 256;
update mapids set locationname = 'Unknown 1F' where mapid = 257;
update mapids set locationname = 'Unknown 2F' where mapid = 258;
update mapids set locationname = 'Unknown 3F' where mapid = 259;
update mapids set locationname = 'Aden Castle' where mapid = 300;
update mapids set locationname = 'Aden Sewer' where mapid = 301;
update mapids set locationname = 'Sepia Dungeon' where mapid = 302;
update mapids set locationname = 'Dream Island' where mapid = 303;
update mapids set locationname = 'Silent Cavern' where mapid = 304;
update mapids set locationname = 'Lastabad Dungeon 1F' where mapid = 307;
update mapids set locationname = 'Lastabad Dungeon 2F' where mapid = 308;
update mapids set locationname = 'Lastabad Dungeon 3F' where mapid = 309;
update mapids set locationname = 'Oum Dungeon' where mapid = 310;
update mapids set locationname = 'Diad Fortress' where mapid = 320;
update mapids set locationname = 'Mineral Dungeon' where mapid = 330;
update mapids set locationname = 'Unknown' where mapid = 340;
update mapids set locationname = 'Giran Traders Village' where mapid = 350;
update mapids set locationname = 'Oren Traders Village' where mapid = 360;
update mapids set locationname = 'Silver Knight Traders Village' where mapid = 370;
update mapids set locationname = 'Great Cavern' where mapid = 400;
update mapids set locationname = 'Sanctuary of Evil' where mapid = 410;
update mapids set locationname = 'Abyss Lake' where mapid = 420;
update mapids set locationname = 'Elemental Grave' where mapid = 430;
update mapids set locationname = 'Pirate Island First Part' where mapid = 440;
update mapids set locationname = 'Pirate Island Dungeon 1F' where mapid = 441;
update mapids set locationname = 'Pirate Island Dungeon 2F' where mapid = 442;
update mapids set locationname = 'Pirate Island Dungeon 3F' where mapid = 443;
update mapids set locationname = 'Pirate Island Dungeon 4F' where mapid = 444;
update mapids set locationname = 'Front Gate of Lastavard' where mapid = 450;
update mapids set locationname = '1st Floor Meeting Area' where mapid = 451;
update mapids set locationname = '1st Floor Dark Warrens' where mapid = 454;
update mapids set locationname = '1st Floor Dark Warrens' where mapid = 455;
update mapids set locationname = '1st Floor Evil Power Summoning Room' where mapid = 456;
update mapids set locationname = '1st Floor Off-Limits Area of Darkness' where mapid = 457;
update mapids set locationname = 'Pirate\'s Isle' where mapid = 480;
update mapids set locationname = 'Underground Training Area' where mapid = 490;
update mapids set locationname = 'Underground Passageway' where mapid = 491;
update mapids set locationname = 'Assassin King\'s Power Room' where mapid = 492;
update mapids set locationname = 'Underground Control Room' where mapid = 493;
update mapids set locationname = 'Underground Punishment Area' where mapid = 494;
update mapids set locationname = 'Underground Duel Area' where mapid = 495;
update mapids set locationname = 'Underground Jail' where mapid = 496;
update mapids set locationname = 'Unknown' where mapid = 535;
update mapids set locationname = 'Unknown' where mapid = 550;
update mapids set locationname = 'Unknown' where mapid = 551;
update mapids set locationname = 'Unknown' where mapid = 552;
update mapids set locationname = 'Unknown' where mapid = 553;
update mapids set locationname = 'Unknown' where mapid = 554;
update mapids set locationname = 'Unknown' where mapid = 555;
update mapids set locationname = 'Unknown' where mapid = 556;
update mapids set locationname = 'Unknown' where mapid = 557;
update mapids set locationname = 'Unknown' where mapid = 558;
update mapids set locationname = 'Hell' where mapid = 666;
update mapids set locationname = 'Ancient Space 1F' where mapid = 2000;
update mapids set locationname = 'Ancient Space 2F' where mapid = 2001;
update mapids set locationname = 'Ancient Space 3F' where mapid = 2002;
update mapids set locationname = 'Ancient Space 4F' where mapid = 2003;
update mapids set locationname = 'Unknown' where mapid = 8011;
update mapids set locationname = 'Unknown' where mapid = 8012;
update mapids set locationname = 'Unknown' where mapid = 8013;
update mapids set locationname = 'Unknown' where mapid = 8014;
update mapids set locationname = 'Unknown' where mapid = 8015;

-- fix all npc names
update npc set name = 'Dark Forester' where npcid = 45851;
update npc set name = 'Dark Elementalist' where npcid = 45852;
update npc set name = 'Cursed Dark Elf Wizard' where npcid = 45853;
update npc set name = 'Guardian of Earth Spirit' where npcid = 45854;
update npc set name = 'Guardian of Water Spirit' where npcid = 45855;
update npc set name = 'Guardian of Wind Spirit' where npcid = 45856;
update npc set name = 'Guardian of Fire Spirit' where npcid = 45857;
update npc set name = 'Guardian of Darkness Spirit' where npcid = 45858;
update npc set name = 'Cursed Dark Elf Wizard' where npcid = 45859;
update npc set name = 'Cursed Dark Elf Wizard' where npcid = 45860;
update npc set name = 'Cursed Dark Elf Warrior' where npcid = 45861;
update npc set name = 'Cursed Dark Elf Warrior' where npcid = 45862;
update npc set name = 'Dread Queen Laia' where npcid = 45863;
update npc set name = 'Cursed Dark Elf Wizard' where npcid = 45864;
update npc set name = 'Cursed Dark Elf Knight' where npcid = 45865;
update npc set name = 'Cursed Dark Elf Knight' where npcid = 45866;
update npc set name = 'Cursed Dark Elf Warrior' where npcid = 45867;
update npc set name = 'Oum Warrior' where npcid = 45868;
update npc set name = 'Cursed Dark Elf Wizard' where npcid = 45869;
update npc set name = 'Cursed Dark Elf Knight' where npcid = 45870;
update npc set name = 'Cursed Dark Elf Knight' where npcid = 45871;
update npc set name = 'Heavy Oum Warrior' where npcid = 45872;
update npc set name = 'Eidlon' where npcid = 45873;
update npc set name = 'Unknown Lizardman' where npcid = 45874;
update npc set name = 'Skeletal Pirate Head' where npcid = 45875;
update npc set name = 'Unknown 45876' where npcid = 45876;
update npc set name = 'Treasure Chest' where npcid = 45877;
update npc set name = 'Spirit of Drake' where npcid = 45878;
update npc set name = 'Goblin of Ordeal' where npcid = 45879;
update npc set name = 'Goblin of Ordeal' where npcid = 45880;
update npc set name = 'Goblin of Ordeal' where npcid = 45881;
update npc set name = 'Goblin of Ordeal' where npcid = 45882;
update npc set name = 'Barnia' where npcid = 50001;
update npc set name = 'Sky' where npcid = 50002;
update npc set name = 'Illdrath' where npcid = 50003;
update npc set name = 'Novice Teleporter' where npcid = 50004;
update npc set name = 'Karen' where npcid = 50005;
update npc set name = 'Coco' where npcid = 50006;
update npc set name = 'Esmeralda' where npcid = 50007;
update npc set name = 'Arena Guide' where npcid = 50008;
update npc set name = 'Ishtar' where npcid = 50009;
update npc set name = 'Novice Teleporter' where npcid = 50010;
update npc set name = 'Kun' where npcid = 50011;
update npc set name = 'Kiyari' where npcid = 50012;
update npc set name = 'Arena Guide' where npcid = 50013;
update npc set name = 'Dilong' where npcid = 50014;
update npc set name = 'Lucas' where npcid = 50015;
update npc set name = 'Zeno' where npcid = 50016;
update npc set name = 'Keith' where npcid = 50017;
update npc set name = 'Coliseum Manager' where npcid = 50018;
update npc set name = 'Deanos' where npcid = 50068;
update npc set name = 'Enya' where npcid = 50069;
update npc set name = 'Lucky' where npcid = 50070;
update npc set name = 'Ishiris' where npcid = 50071;
update npc set name = 'Teleporter Diarus' where npcid = 50072;
update npc set name = 'Teleporter Diabes' where npcid = 50073;
update npc set name = 'Large Cave Teleporter' where npcid = 50074;
update npc set name = 'Fortress Gatekeeper' where npcid = 50075;
update npc set name = 'Orb of Spirit' where npcid = 50076;
update npc set name = 'Orb of Spirit' where npcid = 50077;
update npc set name = 'Orb of Spirit' where npcid = 50078;
update npc set name = 'Explorer\'s Assistant' where npcid = 50081;
update npc set name = 'Unknown 50082' where npcid = 50082;
update npc set name = 'Unknown 50083' where npcid = 50083;
update npc set name = 'Guard' where npcid = 50084;
update npc set name = 'Liri' where npcid = 50111;
update npc set name = 'Jaruman' where npcid = 50115;
update npc set name = 'Beth' where npcid = 50119;
update npc set name = 'Sarah' where npcid = 50520;
update npc set name = 'Saloma' where npcid = 50521;
update npc set name = 'Sigrid' where npcid = 50522;
update npc set name = 'Erma' where npcid = 50523;
update npc set name = 'Emilia' where npcid = 50524;
update npc set name = 'Eulalia' where npcid = 50525;
update npc set name = 'Eleanora' where npcid = 50526;
update npc set name = 'Emma' where npcid = 50527;
update npc set name = 'Osa' where npcid = 50528;
update npc set name = 'Even' where npcid = 50529;
update npc set name = 'Ione' where npcid = 50530;
update npc set name = 'Justine' where npcid = 50531;
update npc set name = 'Geraldine' where npcid = 50532;
update npc set name = 'Joanna' where npcid = 50533;
update npc set name = 'Julia' where npcid = 50534;
update npc set name = 'Juliana' where npcid = 50535;
update npc set name = 'Jilda' where npcid = 50536;
update npc set name = 'Karelia' where npcid = 50537;
update npc set name = 'Carmel' where npcid = 50538;
update npc set name = 'Karine' where npcid = 50539;
update npc set name = 'Catriona' where npcid = 50540;
update npc set name = 'Tessa' where npcid = 50541;
update npc set name = 'Teodora' where npcid = 50542;
update npc set name = 'Tekla' where npcid = 50543;
update npc set name = 'Paulina' where npcid = 50544;
update npc set name = 'Henrietta' where npcid = 50545;
update npc set name = 'Nadine' where npcid = 50546;
update npc set name = 'Nash' where npcid = 50547;
update npc set name = 'Natalia' where npcid = 50548;
update npc set name = 'Nona' where npcid = 50549;
update npc set name = 'Nita' where npcid = 50550;
update npc set name = 'Diana' where npcid = 50551;
update npc set name = 'Doria' where npcid = 50552;
update npc set name = 'Dina' where npcid = 50553;
update npc set name = 'Levins' where npcid = 50554;
update npc set name = 'Lucie' where npcid = 50555;
update npc set name = 'Rociri' where npcid = 50556;
update npc set name = 'Locis' where npcid = 50557;
update npc set name = 'Ressie' where npcid = 50558;
update npc set name = 'Lucinda' where npcid = 50559;
update npc set name = 'Liz' where npcid = 50560;
update npc set name = 'Rija' where npcid = 50561;
update npc set name = 'Mariel' where npcid = 50562;
update npc set name = 'McCauley' where npcid = 50563;
update npc set name = 'Meyo' where npcid = 50564;
update npc set name = 'May' where npcid = 50565;
update npc set name = 'Mella' where npcid = 50566;
update npc set name = 'Morin' where npcid = 50567;
update npc set name = 'Mitchel' where npcid = 50568;
update npc set name = 'Michelli' where npcid = 50569;
update npc set name = 'Mindy' where npcid = 50570;
update npc set name = 'Beverly' where npcid = 50571;
update npc set name = 'Beth' where npcid = 50572;
update npc set name = 'Bella' where npcid = 50573;
update npc set name = 'Bonie' where npcid = 50574;
update npc set name = 'Bobby' where npcid = 50575;
update npc set name = 'Brittainy' where npcid = 50576;
update npc set name = 'Bianca' where npcid = 50577;
update npc set name = 'Violet' where npcid = 50578;
update npc set name = 'Sadie' where npcid = 50579;
update npc set name = 'Cellay' where npcid = 50580;
update npc set name = 'Celina' where npcid = 50581;
update npc set name = 'Sophia' where npcid = 50582;
update npc set name = 'Sherrie' where npcid = 50583;
update npc set name = 'Sibia' where npcid = 50584;
update npc set name = 'Cindy' where npcid = 50585;
update npc set name = 'Sylvia' where npcid = 50586;
update npc set name = 'Arana' where npcid = 50587;
update npc set name = 'Amie' where npcid = 50588;
update npc set name = 'Aberi' where npcid = 50589;
update npc set name = 'Acacia' where npcid = 50590;
update npc set name = 'Angelina' where npcid = 50591;
update npc set name = 'Angelica' where npcid = 50592;
update npc set name = 'Edie' where npcid = 50593;
update npc set name = 'Ebony' where npcid = 50594;
update npc set name = 'Angeline' where npcid = 50595;
update npc set name = 'Odia' where npcid = 50596;
update npc set name = 'Ophelia' where npcid = 50597;
update npc set name = 'Wanda' where npcid = 50598;
update npc set name = 'Isabelle' where npcid = 50599;
update npc set name = 'Genesse' where npcid = 50600;
update npc set name = 'Zenith' where npcid = 50601;
update npc set name = 'Joanne' where npcid = 50602;
update npc set name = 'Judith' where npcid = 50603;
update npc set name = 'Chellany' where npcid = 50604;
update npc set name = 'Karot' where npcid = 50605;
update npc set name = 'Karisha' where npcid = 50606;
update npc set name = 'Candice' where npcid = 50607;
update npc set name = 'Kinin' where npcid = 50608;
update npc set name = 'Tamara' where npcid = 50609;
update npc set name = 'Teresa' where npcid = 50610;
update npc set name = 'Prolance' where npcid = 50611;
update npc set name = 'Florina' where npcid = 50612;
update npc set name = 'Helena' where npcid = 50613;
update npc set name = 'Novita' where npcid = 50614;
update npc set name = 'Dain' where npcid = 50615;
update npc set name = 'Delia' where npcid = 50616;
update npc set name = 'Lorena' where npcid = 50617;
update npc set name = 'Morna' where npcid = 50618;
update npc set name = 'Miriam' where npcid = 50619;
update npc set name = 'Adina' where npcid = 50620;
update npc set name = 'Edry' where npcid = 50621;
update npc set name = 'Elsha' where npcid = 50622;
update npc set name = 'Zenia' where npcid = 50623;
update npc set name = 'Triona' where npcid = 50624;
update npc set name = 'Ancient Person' where npcid = 50625;
update npc set name = 'Dorin' where npcid = 60001;
update npc set name = 'Bahof' where npcid = 60002;
update npc set name = 'Luke' where npcid = 60005;
update npc set name = 'Jianku' where npcid = 60006;
update npc set name = 'Karim' where npcid = 60007;
update npc set name = 'Nodim' where npcid = 60008;
update npc set name = 'Sauram' where npcid = 60009;
update npc set name = 'Kasham' where npcid = 60010;
update npc set name = 'Kuron' where npcid = 60011;
update npc set name = 'Tofen' where npcid = 60012;
update npc set name = 'Axellon' where npcid = 60013;
update npc set name = 'Kriom' where npcid = 60014;
update npc set name = 'Ogi' where npcid = 60015;
update npc set name = 'Juke' where npcid = 60016;
update npc set name = 'Karudim' where npcid = 60017;
update npc set name = 'Calvas' where npcid = 60018;
update npc set name = 'Timpukin' where npcid = 60019;
update npc set name = 'Tulak' where npcid = 60020;
update npc set name = 'Hirim' where npcid = 60021;
update npc set name = 'Borgin' where npcid = 60022;
update npc set name = 'Tarkin' where npcid = 60023;
update npc set name = 'Gotham' where npcid = 60024;
update npc set name = 'Kusian' where npcid = 60025;
update npc set name = 'Orclon' where npcid = 60026;
update npc set name = 'Kuhatin' where npcid = 60027;
update npc set name = 'El' where npcid = 60028;
update npc set name = 'Haidrim' where npcid = 60029;
update npc set name = 'Hakim' where npcid = 60030;
update npc set name = 'Rayearth' where npcid = 60031;
update npc set name = 'Storage House Keeper Garin' where npcid = 60032;
update npc set name = 'Storage House Keeper Gaul' where npcid = 60033;
update npc set name = 'Kuud' where npcid = 60034;
update npc set name = 'Zidar' where npcid = 60035;
update npc set name = 'Tigus' where npcid = 60036;
update npc set name = 'Unknown 60037' where npcid = 60037;
update npc set name = 'Guard' where npcid = 60502;
update npc set name = 'Ranger' where npcid = 60503;
update npc set name = 'Ranger' where npcid = 60504;
update npc set name = 'Guard' where npcid = 60505;
update npc set name = 'Guard' where npcid = 60506;
update npc set name = 'Guard' where npcid = 60507;
update npc set name = 'Guard' where npcid = 60508;
update npc set name = 'Guard' where npcid = 60509;
update npc set name = 'Guard' where npcid = 60510;
update npc set name = 'Court Guard' where npcid = 60511;
update npc set name = 'Court Guard' where npcid = 60512;
update npc set name = 'Guard' where npcid = 60513;
update npc set name = 'Court Guard' where npcid = 60514;
update npc set name = 'Kent Mercenary Squad' where npcid = 60515;
update npc set name = 'Kent Mercenary Squad' where npcid = 60516;
update npc set name = 'Guard' where npcid = 60517;
update npc set name = 'Guard' where npcid = 60518;
update npc set name = 'Blue Sharks' where npcid = 60519;
update npc set name = 'Kent Mercenary Squad' where npcid = 60520;
update npc set name = 'Kent Mercenary Squad' where npcid = 60521;
update npc set name = 'Guard' where npcid = 60522;
update npc set name = 'Guard' where npcid = 60523;
update npc set name = 'Court Guard' where npcid = 60525;
update npc set name = 'Giran Mercenary Squad' where npcid = 60526;
update npc set name = 'Giran Mercenary Squad' where npcid = 60527;
update npc set name = 'Gludin Guard', nameid = 'Gludin $240' where npcid = 60528;
update npc set name = 'Court Guard' where npcid = 60529;
update npc set name = 'Dwarf Guard' where npcid = 60530;
update npc set name = 'Dwarf Guard' where npcid = 60531;
update npc set name = 'Unknown 60532', nameid = 'Unknown 60532' where npcid = 60532;
update npc set name = 'Aden Castle Guard', nameid = 'Aden Castle $240' where npcid = 60533;
update npc set name = 'Aden Castle Guard', nameid = 'Aden Castle $240' where npcid = 60534;
update npc set name = 'Aden Court Guard' where npcid = 60535;
update npc set name = 'Aden Court Guard' where npcid = 60536;
update npc set name = 'Aden Guard' where npcid = 60537;
update npc set name = 'Aden Guard' where npcid = 60538;
update npc set name = 'Aden Mercenary Squad' where npcid = 60539;
update npc set name = 'Aden Mercenary Squad' where npcid = 60540;
update npc set name = 'Guard' where npcid = 60541;
update npc set name = 'Guard' where npcid = 60542;
update npc set name = 'Guard' where npcid = 60543;
update npc set name = 'Guard' where npcid = 60544;
update npc set name = 'Guard' where npcid = 60545;
update npc set name = 'Guard' where npcid = 60546;
update npc set name = 'Guard' where npcid = 60547;
update npc set name = 'Guard' where npcid = 60548;
update npc set name = 'Court Guard' where npcid = 60549;
update npc set name = 'Court Guard' where npcid = 60550;
update npc set name = 'Windawood Castle Guard' where npcid = 60551;
update npc set name = 'Court Guard' where npcid = 60552;
update npc set name = 'Windawood Mercenary Squad' where npcid = 60553;
update npc set name = 'Windawood Mercenary Squad' where npcid = 60554;
update npc set name = 'Unknown 60555', nameid = 'Unknown 60555' where npcid = 60555;
update npc set name = 'Guard' where npcid = 60556;
update npc set name = 'Guard' where npcid = 60557;
update npc set name = 'Gerard Mercenary Squad' where npcid = 60558;
update npc set name = 'Gerard Mercenary Squad' where npcid = 60559;
update npc set name = 'Orcish Court Guard' where npcid = 60560;
update npc set name = 'Court Guard' where npcid = 60561;
update npc set name = 'Court Guard' where npcid = 60562;
update npc set name = 'Heine Guard' where npcid = 60563;
update npc set name = 'Unknown 60564', nameid = 'Unknown 60564' where npcid = 60564;
update npc set name = 'Unknown 60565', nameid = 'Unknown 60565' where npcid = 60565;
update npc set name = 'Dark Elf Ranger' where npcid = 60566;
update npc set name = 'Guard' where npcid = 60567;
update npc set name = 'Rose' where npcid = 70001;
update npc set name = 'Sasha' where npcid = 70002;
update npc set name = 'Siriss' where npcid = 70003;
update npc set name = 'Unknown 70004' where npcid = 70004;
update npc set name = 'Pago' where npcid = 70005;
update npc set name = 'Kiris' where npcid = 70006;
update npc set name = 'Tina' where npcid = 70007;
update npc set name = 'Fraoun' where npcid = 70008;
update npc set name = 'Gereng' where npcid = 70009;
update npc set name = 'Balsim' where npcid = 70010;
update npc set name = 'Harbor Master' where npcid = 70011;
update npc set name = 'Selena' where npcid = 70012;
update npc set name = 'Cole' where npcid = 70013;
update npc set name = 'Pandora' where npcid = 70014;
update npc set name = 'Pasim' where npcid = 70025;
update npc set name = 'Derek' where npcid = 70026;
update npc set name = 'Randal' where npcid = 70028;
update npc set name = 'Margaret' where npcid = 70029;
update npc set name = 'Mayer' where npcid = 70030;
update npc set name = 'Molly' where npcid = 70031;
update npc set name = 'Vergil' where npcid = 70032;
update npc set name = 'Verita' where npcid = 70033;
update npc set name = 'Vincent' where npcid = 70034;
update npc set name = 'Izawa' where npcid = 70035;
update npc set name = 'Stella' where npcid = 70036;
update npc set name = 'Aden Chamber of Commerce' where npcid = 70037;
update npc set name = 'Evert' where npcid = 70038;
update npc set name = 'Werner' where npcid = 70039;
update npc set name = 'Jason' where npcid = 70040;
update npc set name = 'Maeno' where npcid = 70041;
update npc set name = 'Tanaka' where npcid = 70042;
update npc set name = 'Philip' where npcid = 70043;
update npc set name = 'Ralf' where npcid = 70044;
update npc set name = 'Berry' where npcid = 70045;
update npc set name = 'Jin' where npcid = 70046;
update npc set name = 'Defman' where npcid = 70047;
update npc set name = 'Raon' where npcid = 70048;
update npc set name = 'Rozen' where npcid = 70049;
update npc set name = 'Ruky' where npcid = 70050;
update npc set name = 'Magus' where npcid = 70051;
update npc set name = 'Melissa' where npcid = 70052;
update npc set name = 'Shara' where npcid = 70053;
update npc set name = 'Sabin' where npcid = 70054;
update npc set name = 'Ashinnue' where npcid = 70055;
update npc set name = 'Jode' where npcid = 70056;
update npc set name = 'Catherine' where npcid = 70057;
update npc set name = 'Fega' where npcid = 70058;
update npc set name = 'Dico' where npcid = 70059;
update npc set name = 'Linda' where npcid = 70060;
update npc set name = 'Mandra' where npcid = 70061;
update npc set name = 'Varyeth' where npcid = 70062;
update npc set name = 'Bius' where npcid = 70063;
update npc set name = 'Aden Chamber of Commerce' where npcid = 70064;
update npc set name = 'Enke' where npcid = 70065;
update npc set name = 'Kreister' where npcid = 70066;
update npc set name = 'Pagoru' where npcid = 70067;
update npc set name = 'Franko' where npcid = 70068;
update npc set name = 'Momo' where npcid = 70069;
update npc set name = 'Velisa' where npcid = 70070;
update npc set name = 'Ashur' where npcid = 70071;
update npc set name = 'Elmina' where npcid = 70072;
update npc set name = 'Glen' where npcid = 70073;
update npc set name = 'Mellin' where npcid = 70074;
update npc set name = 'Miranda' where npcid = 70075;
update npc set name = 'Aden Chamber of Commerce' where npcid = 70076;
update npc set name = 'Rodney' where npcid = 70077;
update npc set name = 'Orcm' where npcid = 70078;
update npc set name = 'Jackson' where npcid = 70079;
update npc set name = 'Horun' where npcid = 70080;
update npc set name = 'Buakheu' where npcid = 70081;
update npc set name = 'Britt' where npcid = 70082;
update npc set name = 'Shivan' where npcid = 70083;
update npc set name = 'Elly' where npcid = 70084;
update npc set name = 'Old' where npcid = 70085;
update npc set name = 'Isvall' where npcid = 70086;
update npc set name = 'Sedia' where npcid = 70087;
update npc set name = 'Squalid' where npcid = 70088;
update npc set name = 'Oblivion' where npcid = 70089;
update npc set name = 'Chicky' where npcid = 70090;
update npc set name = 'Tilon' where npcid = 70091;
update npc set name = 'Trader Emart' where npcid = 70092;
update npc set name = 'Trader Carupu' where npcid = 70093;
update npc set name = 'Duran' where npcid = 70094;
update npc set name = 'Duron' where npcid = 70095;
update npc set name = 'Millay' where npcid = 70096;
update npc set name = 'Foni' where npcid = 70097;
update npc set name = 'Bobo' where npcid = 70098;
update npc set name = 'Kuper' where npcid = 70099;
update npc set name = 'Lengo' where npcid = 70100;
update npc set name = 'Fiin' where npcid = 70101;
update npc set name = 'Judice' where npcid = 70102;
update npc set name = 'Eban' where npcid = 70501;
update npc set name = 'Arena Guide' where npcid = 70502;
update npc set name = 'Unknown 70505' where npcid = 70505;
update npc set name = 'Ruba' where npcid = 70506;
update npc set name = 'Rion' where npcid = 70507;
update npc set name = 'Weapon Enchanter' where npcid = 70508;
update npc set name = 'Armor Enchanter' where npcid = 70509;
update npc set name = 'Polymorph Magician' where npcid = 70510;
update npc set name = 'Healer' where npcid = 70512;
update npc set name = 'Peria' where npcid = 70513;
update npc set name = 'Haste Master' where npcid = 70514;
update npc set name = 'Mubo' where npcid = 70515;
update npc set name = 'Belgeter' where npcid = 70516;
update npc set name = 'Cuse' where npcid = 70517;
update npc set name = 'Tio' where npcid = 70518;
update npc set name = 'Peria' where npcid = 70519;
update npc set name = 'Guard' where npcid = 70521;
update npc set name = 'Gunter' where npcid = 70522;
update npc set name = 'Ladar' where npcid = 70523;
update npc set name = 'Lavienue' where npcid = 70524;
update npc set name = 'Lien' where npcid = 70525;
update npc set name = 'Raidar' where npcid = 70526;
update npc set name = 'Terry' where npcid = 70527;
update npc set name = 'Village Manager' where npcid = 70528;
update npc set name = 'Mona' where npcid = 70529;
update npc set name = 'Goddess of Atonement' where npcid = 70530;
update npc set name = 'Jem' where npcid = 70531;
update npc set name = 'Johnson' where npcid = 70532;
update npc set name = 'Judice' where npcid = 70533;
update npc set name = 'Secratary to the Mayor' where npcid = 70534;
update npc set name = 'Unknown 70535' where npcid = 70535;
update npc set name = 'Touma' where npcid = 70536;
update npc set name = 'Farlin' where npcid = 70537;
update npc set name = 'Blood Pledge Administrator' where npcid = 70538;
update npc set name = 'Unknown 70539' where npcid = 70539;
update npc set name = 'Guard' where npcid = 70541;
update npc set name = 'Gayle' where npcid = 70542;
update npc set name = 'Unknown 70543' where npcid = 70543;
update npc set name = 'Rick' where npcid = 70544;
update npc set name = 'Richard' where npcid = 70545;
update npc set name = 'Village Manager' where npcid = 70546;
update npc set name = 'Weapon Enchanter' where npcid = 70547;
update npc set name = 'Unknown 70548' where npcid = 70548;
update npc set name = 'Gatekeeper' where npcid = 70549;
update npc set name = 'Armor Enchanter' where npcid = 70550;
update npc set name = 'Unknown 70551' where npcid = 70551;
update npc set name = 'Unknown 70552' where npcid = 70552;
update npc set name = 'Ishmael' where npcid = 70553;
update npc set name = 'Zero' where npcid = 70554;
update npc set name = 'Jim' where npcid = 70555;
update npc set name = 'Secratary to the Mayor' where npcid = 70556;
update npc set name = 'Cana' where npcid = 70557;
update npc set name = 'Kent Mercenary Squad' where npcid = 70558;
update npc set name = 'Kent Mercenary Squad' where npcid = 70559;
update npc set name = 'Blood Pledge Administrator' where npcid = 70560;
update npc set name = 'Unknown 70561', nameid = 'Unknown 70561' where npcid = 70561;
update npc set name = 'Mercenary Captain Hunt' where npcid = 70562;
update npc set name = 'Guard' where npcid = 70564;
update npc set name = 'Unknown 70566' where npcid = 70566;
update npc set name = 'Village Manager' where npcid = 70567;
update npc set name = 'Yuno' where npcid = 70568;
update npc set name = 'Jaint' where npcid = 70569;
update npc set name = 'Jyta' where npcid = 70570;
update npc set name = 'Unknown 70571' where npcid = 70571;
update npc set name = 'Secratary to the Mayor' where npcid = 70572;
update npc set name = 'Farbo' where npcid = 70573;
update npc set name = 'Guard' where npcid = 70575;
update npc set name = 'Garth' where npcid = 70576;
update npc set name = 'Auctioneer' where npcid = 70577;
update npc set name = 'Unknown 70578' where npcid = 70578;
update npc set name = 'Unknown 70579' where npcid = 70579;
update npc set name = 'Unknown 70580' where npcid = 70580;
update npc set name = 'Gulian' where npcid = 70581;
update npc set name = 'Neil' where npcid = 70582;
update npc set name = 'Nelson' where npcid = 70583;
update npc set name = 'Daria' where npcid = 70584;
update npc set name = 'Damon' where npcid = 70585;
update npc set name = 'Daisy' where npcid = 70586;
update npc set name = 'Doris' where npcid = 70587;
update npc set name = 'Unknown 70588' where npcid = 70588;
update npc set name = 'Laban' where npcid = 70589;
update npc set name = 'Luke' where npcid = 70590;
update npc set name = 'Lina' where npcid = 70591;
update npc set name = 'Leal' where npcid = 70592;
update npc set name = 'Manus' where npcid = 70593;
update npc set name = 'Village Manager' where npcid = 70594;
update npc set name = 'Mandel' where npcid = 70595;
update npc set name = 'Malcom' where npcid = 70596;
update npc set name = 'Moran' where npcid = 70597;
update npc set name = 'Moria' where npcid = 70598;
update npc set name = 'Weapon Enchanter' where npcid = 70599;
update npc set name = 'Gatekeeper' where npcid = 70600;
update npc set name = 'Armor Enchanter' where npcid = 70601;
update npc set name = 'Velma' where npcid = 70602;
update npc set name = 'Bruno' where npcid = 70603;
update npc set name = 'Bridget' where npcid = 70604;
update npc set name = 'Blaise' where npcid = 70605;
update npc set name = 'Victor' where npcid = 70606;
update npc set name = 'Sarsha' where npcid = 70607;
update npc set name = 'Shalina' where npcid = 70608;
update npc set name = 'Sally' where npcid = 70609;
update npc set name = 'Sherwin' where npcid = 70610;
update npc set name = 'Goddess of Atonement' where npcid = 70611;
update npc set name = 'Sidney' where npcid = 70612;
update npc set name = 'Amanda' where npcid = 70613;
update npc set name = 'Anton' where npcid = 70614;
update npc set name = 'Alda' where npcid = 70615;
update npc set name = 'Aldred' where npcid = 70616;
update npc set name = 'Almon' where npcid = 70617;
update npc set name = 'Andrew' where npcid = 70618;
update npc set name = 'Alice' where npcid = 70619;
update npc set name = 'Eban' where npcid = 70620;
update npc set name = 'Evelyn' where npcid = 70621;
update npc set name = 'Eliza' where npcid = 70622;
update npc set name = 'Orville' where npcid = 70623;
update npc set name = 'Oliver' where npcid = 70624;
update npc set name = 'Iola' where npcid = 70625;
update npc set name = 'Jack' where npcid = 70626;
update npc set name = 'Jenny' where npcid = 70627;
update npc set name = 'Jessy' where npcid = 70628;
update npc set name = 'James' where npcid = 70629;
update npc set name = 'Giles' where npcid = 70630;
update npc set name = 'Secratary to the Mayor' where npcid = 70631;
update npc set name = 'Kevin' where npcid = 70632;
update npc set name = 'Colbert' where npcid = 70633;
update npc set name = 'Tanya' where npcid = 70634;
update npc set name = 'Tyrus' where npcid = 70635;
update npc set name = 'Terry' where npcid = 70636;
update npc set name = 'Tovia' where npcid = 70637;
update npc set name = 'Tracey' where npcid = 70638;
update npc set name = 'Ferdinand' where npcid = 70639;
update npc set name = 'Pierre' where npcid = 70640;
update npc set name = 'Helen' where npcid = 70641;
update npc set name = 'Blood Pledge Administrator' where npcid = 70644;
update npc set name = 'Guard' where npcid = 70646;
update npc set name = 'Gavin' where npcid = 70647;
update npc set name = 'Daley' where npcid = 70648;
update npc set name = 'Lary' where npcid = 70649;
update npc set name = 'Horse of Lary' where npcid = 70650;
update npc set name = 'Lary\'s Soldier' where npcid = 70651;
update npc set name = 'Lary\'s Assistant' where npcid = 70652;
update npc set name = 'Marshall' where npcid = 70653;
update npc set name = 'Village Manager' where npcid = 70654;
update npc set name = 'Weapon Enchanter' where npcid = 70655;
update npc set name = 'Gatekeeper' where npcid = 70656;
update npc set name = 'Armor Enchanter' where npcid = 70657;
update npc set name = 'Goddess of Atonement' where npcid = 70658;
update npc set name = 'Atara' where npcid = 70659;
update npc set name = 'Unknown 70660' where npcid = 70660;
update npc set name = 'Unknown 70661' where npcid = 70661;
update npc set name = 'Ivelviin' where npcid = 70662;
update npc set name = 'Secratary to the Mayor' where npcid = 70663;
update npc set name = 'Cove' where npcid = 70664;
update npc set name = 'Potempin' where npcid = 70665;
update npc set name = 'Freckson' where npcid = 70666;
update npc set name = 'Blood Pledge Administrator' where npcid = 70667;
update npc set name = 'Auctioneer' where npcid = 70669;
update npc set name = 'Cray' where npcid = 70670;
update npc set name = 'Nose' where npcid = 70671;
update npc set name = 'Raphael' where npcid = 70672;
update npc set name = 'Unknown 70673' where npcid = 70673;
update npc set name = 'Reona' where npcid = 70674;
update npc set name = 'Rose' where npcid = 70675;
update npc set name = 'Ryumiel' where npcid = 70676;
update npc set name = 'Lilia' where npcid = 70677;
update npc set name = 'Unknown 70678' where npcid = 70678;
update npc set name = 'Marja' where npcid = 70679;
update npc set name = 'Mikey' where npcid = 70680;
update npc set name = 'Matilda' where npcid = 70681;
update npc set name = 'Marx' where npcid = 70682;
update npc set name = 'Montes' where npcid = 70683;
update npc set name = 'Words of Montes' where npcid = 70684;
update npc set name = 'Words of Montes' where npcid = 70685;
update npc set name = 'Weapon Enchanter' where npcid = 70686;
update npc set name = 'Gatekeeper' where npcid = 70687;
update npc set name = 'Muras' where npcid = 70688;
update npc set name = 'Misa' where npcid = 70689;
update npc set name = 'Bamute' where npcid = 70690;
update npc set name = 'Barbara' where npcid = 70691;
update npc set name = 'Armor Enchanter' where npcid = 70692;
update npc set name = 'Buckley' where npcid = 70693;
update npc set name = 'Brutus' where npcid = 70694;
update npc set name = 'Biust' where npcid = 70695;
update npc set name = 'Bindro' where npcid = 70696;
update npc set name = 'Seratti' where npcid = 70697;
update npc set name = 'Selma' where npcid = 70698;
update npc set name = 'Sheryan' where npcid = 70699;
update npc set name = 'Sabin' where npcid = 70700;
update npc set name = 'Goddess Agata' where npcid = 70701;
update npc set name = 'Goddess Ariel' where npcid = 70702;
update npc set name = 'Aden Court Guard' where npcid = 70703;
update npc set name = 'Aden Court Guard' where npcid = 70704;
update npc set name = 'Arin' where npcid = 70705;
update npc set name = 'Aquin' where npcid = 70706;
update npc set name = 'Eno' where npcid = 70707;
update npc set name = 'Affleck' where npcid = 70708;
update npc set name = 'Elleanor' where npcid = 70709;
update npc set name = 'Unknown 70710' where npcid = 70710;
update npc set name = 'Jennifer' where npcid = 70712;
update npc set name = 'Jessica' where npcid = 70713;
update npc set name = 'Jaimy' where npcid = 70714;
update npc set name = 'Jimu' where npcid = 70715;
update npc set name = 'Chobi' where npcid = 70716;
update npc set name = 'Karas' where npcid = 70717;
update npc set name = 'Kenihi' where npcid = 70718;
update npc set name = 'Calvin' where npcid = 70719;
update npc set name = 'Unknown 70720' where npcid = 70720;
update npc set name = 'Timon' where npcid = 70721;
update npc set name = 'Paruit' where npcid = 70722;
update npc set name = 'Pau' where npcid = 70723;
update npc set name = 'Heit' where npcid = 70724;
update npc set name = 'Unknown 70726' where npcid = 70726;
update npc set name = 'Unknown 70727' where npcid = 70727;
update npc set name = 'Unknown 70728' where npcid = 70728;
update npc set name = 'Unknown 70729' where npcid = 70729;
update npc set name = 'Unknown 70730' where npcid = 70730;
update npc set name = 'Unknown 70731' where npcid = 70731;
update npc set name = 'Unknown 70732' where npcid = 70732;
update npc set name = 'Unknown 70733' where npcid = 70733;
update npc set name = 'Garuga' where npcid = 70735;
update npc set name = 'Derian' where npcid = 70736;
update npc set name = 'Dekan' where npcid = 70737;
update npc set name = 'Defuri' where npcid = 70738;
update npc set name = 'Dicarding' where npcid = 70739;
update npc set name = 'Soldier of Dicarding' where npcid = 70740;
update npc set name = 'Dima' where npcid = 70741;
update npc set name = 'Detector' where npcid = 70742;
update npc set name = 'Lazloth' where npcid = 70743;
update npc set name = 'Roku' where npcid = 70745;
update npc set name = 'Rotus' where npcid = 70746;
update npc set name = 'Lulu' where npcid = 70747;
update npc set name = 'Unknown 70750' where npcid = 70750;
update npc set name = 'Brad' where npcid = 70751;
update npc set name = 'Biyan' where npcid = 70752;
update npc set name = 'Bion' where npcid = 70753;
update npc set name = 'Unknown 70754' where npcid = 70754;
update npc set name = 'Unknown 70755' where npcid = 70755;
update npc set name = 'Moria' where npcid = 70756;
update npc set name = 'Sabin' where npcid = 70758;
update npc set name = 'Unknown 70759' where npcid = 70759;
update npc set name = 'Ellyonne' where npcid = 70760;
update npc set name = 'Karif' where npcid = 70762;
update npc set name = 'Talass' where npcid = 70763;
update npc set name = 'Taus' where npcid = 70764;
update npc set name = 'Tifany' where npcid = 70765;
update npc set name = 'Paper Man' where npcid = 70766;
update npc set name = 'Haro' where npcid = 70767;
update npc set name = 'Guard' where npcid = 70769;
update npc set name = 'Deker' where npcid = 70770;
update npc set name = 'Raidar' where npcid = 70772;
update npc set name = 'Weapon Enchanter' where npcid = 70777;
update npc set name = 'Armor Enchanter' where npcid = 70780;
update npc set name = 'Search Ant' where npcid = 70782;
update npc set name = 'Othmond' where npcid = 70783;
update npc set name = 'Windawood Mercenary Squad' where npcid = 70785;
update npc set name = 'Windawood Mercenary Squad' where npcid = 70786;
update npc set name = 'Windawood Head of Mercenary Squad' where npcid = 70787;
update npc set name = 'Unknown 70791' where npcid = 70791;
update npc set name = 'Guard' where npcid = 70793;
update npc set name = 'Gerard Mercenary Squad' where npcid = 70795;
update npc set name = 'Anotte' where npcid = 70803;
update npc set name = 'Guard' where npcid = 70809;
update npc set name = 'Nenani Guard' where npcid = 70810;
update npc set name = 'Rohan' where npcid = 70812;
update npc set name = 'Ruu Duda-Mara' where npcid = 70813;
update npc set name = 'Ruka' where npcid = 70814;
update npc set name = 'Weapon Enchanter' where npcid = 70816;
update npc set name = 'Gatekeeper' where npcid = 70817;
update npc set name = 'Bazure Atuba' where npcid = 70818;
update npc set name = 'Bob' where npcid = 70819;
update npc set name = 'Armor Enchanter' where npcid = 70820;
update npc set name = 'Sanita' where npcid = 70821;
update npc set name = 'Saghem Atuba' where npcid = 70822;
update npc set name = 'Goddess of Atonement' where npcid = 70823;
update npc set name = 'Assassin Master\'s Apprentice' where npcid = 70824;
update npc set name = 'Ellne' where npcid = 70825;
update npc set name = 'Oth' where npcid = 70826;
update npc set name = 'Orcish Court Guard' where npcid = 70827;
update npc set name = 'Ofo' where npcid = 70828;
update npc set name = 'Woodford' where npcid = 70829;
update npc set name = 'Secretary to the Mayor' where npcid = 70830;
update npc set name = 'Kentu Neruga' where npcid = 70831;
update npc set name = 'Taga Rova' where npcid = 70832;
update npc set name = 'Tommy' where npcid = 70833;
update npc set name = 'Torban' where npcid = 70834;
update npc set name = 'Hanna' where npcid = 70835;
update npc set name = 'Hans' where npcid = 70836;
update npc set name = 'Narhen' where npcid = 70837;
update npc set name = 'Nerupa' where npcid = 70838;
update npc set name = 'Doett' where npcid = 70839;
update npc set name = 'Robiel' where npcid = 70840;
update npc set name = 'Luudiel' where npcid = 70841;
update npc set name = 'Marba' where npcid = 70842;
update npc set name = 'Morien' where npcid = 70843;
update npc set name = 'Unknown 70844' where npcid = 70844;
update npc set name = 'Aras' where npcid = 70845;
update npc set name = 'Arachne' where npcid = 70846;
update npc set name = 'Est' where npcid = 70847;
update npc set name = 'Ent' where npcid = 70848;
update npc set name = 'Theodore' where npcid = 70849;
update npc set name = 'Pan' where npcid = 70850;
update npc set name = 'Fairy' where npcid = 70851;
update npc set name = 'Hurindalien' where npcid = 70854;
update npc set name = 'Gayle' where npcid = 70856;
update npc set name = 'Heine Guard' where npcid = 70857;
update npc set name = 'Derick' where npcid = 70858;
update npc set name = 'Velma' where npcid = 70859;
update npc set name = 'Village Manager' where npcid = 70860;
update npc set name = 'Weapon Enchanter' where npcid = 70861;
update npc set name = 'Heine Gatekeeper' where npcid = 70862;
update npc set name = 'Heine Gatekeeper' where npcid = 70863;
update npc set name = 'Vaiger' where npcid = 70864;
update npc set name = 'Armor Enchanter' where npcid = 70865;
update npc set name = 'Unknown 70866' where npcid = 70866;
update npc set name = 'Shannon' where npcid = 70867;
update npc set name = 'Stra' where npcid = 70868;
update npc set name = 'Unknown 70869' where npcid = 70869;
update npc set name = 'Arina' where npcid = 70870;
update npc set name = 'Annabel' where npcid = 70871;
update npc set name = 'Eveurol' where npcid = 70872;
update npc set name = 'Ellan' where npcid = 70873;
update npc set name = 'Elina' where npcid = 70874;
update npc set name = 'Oriel' where npcid = 70875;
update npc set name = 'Secretary to the Mayor' where npcid = 70876;
update npc set name = 'Trion' where npcid = 70877;
update npc set name = 'Felix' where npcid = 70878;
update npc set name = 'Unknown 70879' where npcid = 70879;
update npc set name = 'Fisher' where npcid = 70880;
update npc set name = 'Heine Mercenary Squad' where npcid = 70881;
update npc set name = 'Vaiger' where npcid = 70882;
update npc set name = 'Unknown 70883' where npcid = 70883;
update npc set name = 'Blood Pledge Administrator' where npcid = 70884;
update npc set name = 'Unknown 70886' where npcid = 70886;
update npc set name = 'Granik' where npcid = 70887;
update npc set name = 'Derin' where npcid = 70888;
update npc set name = 'Ramune' where npcid = 70889;
update npc set name = 'Rabor' where npcid = 70890;
update npc set name = 'Rondo' where npcid = 70891;
update npc set name = 'Ronde' where npcid = 70892;
update npc set name = 'Ronde\'s Horse' where npcid = 70893;
update npc set name = 'Ronde\'s Bodyguard' where npcid = 70894;
update npc set name = 'Personal Assassin of Bludika' where npcid = 70896;
update npc set name = 'Bishop' where npcid = 70897;
update npc set name = 'Seria' where npcid = 70898;
update npc set name = 'Unknown 70899' where npcid = 70899;
update npc set name = 'Ellvienue' where npcid = 70900;
update npc set name = 'Jeti' where npcid = 70901;
update npc set name = 'Kalynue' where npcid = 70902;
update npc set name = 'Kan\'s Guard' where npcid = 70903;
update npc set name = 'Koup' where npcid = 70904;
update npc set name = 'Unknown 70905' where npcid = 70905;
update npc set name = 'Personal Assassin of Kima' where npcid = 70907;
update npc set name = 'Pierce' where npcid = 70908;
update npc set name = 'Pierot' where npcid = 70909;
update npc set name = 'Hadesty' where npcid = 70910;
update npc set name = 'Hamud' where npcid = 70911;
update npc set name = 'Miner Oum' where npcid = 70912;
update npc set name = 'Miner Oum' where npcid = 70913;
update npc set name = 'Unknown 70914' where npcid = 70914;
update npc set name = 'Unknown 70915' where npcid = 70915;
update npc set name = 'Redin' where npcid = 70916;
update npc set name = 'Burns' where npcid = 70917;
update npc set name = 'Unknown 70918' where npcid = 70918;
update npc set name = 'Smiter' where npcid = 70919;
update npc set name = 'Aden Reconnaissance Soldier' where npcid = 70920;
update npc set name = 'Unknown 70921' where npcid = 70921;
update npc set name = 'Oum' where npcid = 70922;
update npc set name = 'Olle' where npcid = 70923;
update npc set name = 'Unknown Oum',  nameid = 'Unknown $3124' where npcid = 70924;
update npc set name = 'Elder Oum' where npcid = 70925;
update npc set name = 'Unknown 70926' where npcid = 70926;
update npc set name = 'Coderage' where npcid = 70927;
update npc set name = 'Tristan' where npcid = 70928;
update npc set name = 'Unknown 70929' where npcid = 70929;
update npc set name = 'Unknown 70930' where npcid = 70930;
update npc set name = 'Unknown 70931' where npcid = 70931;
update npc set name = 'Doyle' where npcid = 70932;
update npc set name = 'Doyle\'s Dog' where npcid = 70933;
update npc set name = 'Resta' where npcid = 70934;
update npc set name = 'Roberto' where npcid = 70935;
update npc set name = 'Rooney' where npcid = 70936;
update npc set name = 'Rudien' where npcid = 70937;
update npc set name = 'Lukein' where npcid = 70938;
update npc set name = 'Lupus' where npcid = 70939;
update npc set name = 'Lizardman Elder' where npcid = 70940;
update npc set name = 'Young Lizardman Warrior' where npcid = 70941;
update npc set name = 'Monett' where npcid = 70942;
update npc set name = 'Berik' where npcid = 70943;
update npc set name = 'Shian' where npcid = 70944;
update npc set name = 'Simizz' where npcid = 70945;
update npc set name = 'Enishia' where npcid = 70946;
update npc set name = 'Exhausted Lizardman Warrior' where npcid = 70947;
update npc set name = 'Cadmus' where npcid = 70948;
update npc set name = 'Karu' where npcid = 70949;
update npc set name = 'Kamit' where npcid = 70950;
update npc set name = 'Spirit of Kamyla' where npcid = 70951;
update npc set name = 'Franko' where npcid = 70952;
update npc set name = 'Unknown 70954' where npcid = 70954;
update npc set name = 'Unknown 70955' where npcid = 70955;
update npc set name = 'Lesser Demon' where npcid = 70956;
update npc set name = 'Roy' where npcid = 70957;
update npc set name = 'Unknown 70958' where npcid = 70958;
update npc set name = 'Unknown 70959' where npcid = 70959;
update npc set name = 'Unknown 70960' where npcid = 70960;
update npc set name = 'Unknown 70961' where npcid = 70961;
update npc set name = 'Unknown 70962' where npcid = 70962;
update npc set name = 'Incarnation of Varlok' where npcid = 70963;
update npc set name = 'Basch' where npcid = 70964;
update npc set name = 'Shackled Aden Soldier' where npcid = 70965;
update npc set name = 'Shackled Aden Soldier' where npcid = 70966;
update npc set name = 'Shackled Aden Soldier' where npcid = 70967;
update npc set name = 'Unknown 70968' where npcid = 70968;
update npc set name = 'Unknown 70969' where npcid = 70969;
update npc set name = 'Priest of Corruption' where npcid = 70972;
update npc set name = 'Fesco' where npcid = 70973;
update npc set name = 'Unknown 70974' where npcid = 70974;
update npc set name = 'Unknown 70975' where npcid = 70975;
update npc set name = 'Unknown 70976' where npcid = 70976;
update npc set name = 'Unknown 70977' where npcid = 70977;
update npc set name = 'Unknown 70978' where npcid = 70978;
update npc set name = 'Unknown 70979' where npcid = 70979;
update npc set name = 'Liri' where npcid = 70980;
update npc set name = 'Hen' where npcid = 70981;
update npc set name = 'Duck' where npcid = 70982;
update npc set name = 'Pig' where npcid = 70983;
update npc set name = 'Gatekeeper' where npcid = 70985;
update npc set name = 'Gatekeeper' where npcid = 70986;
update npc set name = 'Gatekeeper' where npcid = 70987;
update npc set name = 'Gatekeeper' where npcid = 70988;
update npc set name = 'Gatekeeper' where npcid = 70989;
update npc set name = 'Gatekeeper' where npcid = 70990;
update npc set name = 'Gatekeeper' where npcid = 70991;
update npc set name = 'Gatekeeper' where npcid = 70992;
update npc set name = 'Gatekeeper' where npcid = 70993;
update npc set name = 'Gatekeeper' where npcid = 70994;
update npc set name = 'Gatekeeper' where npcid = 70995;
update npc set name = 'Gatekeeper' where npcid = 70996;
update npc set name = 'Unknown 70997' where npcid = 70997;
update npc set name = 'Unknown 70998' where npcid = 70998;
update npc set name = 'Unknown 70999' where npcid = 70999;
update npc set name = 'Unknown 71000' where npcid = 71000;
update npc set name = 'Unknown 71001' where npcid = 71001;
update npc set name = 'Unknown 71002' where npcid = 71002;
update npc set name = 'Unknown 71003' where npcid = 71003;
update npc set name = 'Unknown 71004' where npcid = 71004;
update npc set name = 'Unknown 71005' where npcid = 71005;
update npc set name = 'Unknown 71006' where npcid = 71006;
update npc set name = 'Unknown 71007' where npcid = 71007;
update npc set name = 'Message Board' where npcid = 72008;
update npc set name = 'Unknown 71009' where npcid = 71009;
update npc set name = 'Unknown 71010' where npcid = 71010;
update npc set name = 'Unknown 71011' where npcid = 71011;
update npc set name = 'Unknown 71012' where npcid = 71012;
update npc set name = 'Karen' where npcid = 71013;
update npc set name = 'Unknown 71014' where npcid = 71014;
update npc set name = 'Unknown 71015' where npcid = 71015;
update npc set name = 'Unknown 71016' where npcid = 71016;
update npc set name = 'Unknown 71017' where npcid = 71017;
update npc set name = 'Unknown 71018' where npcid = 71018;
update npc set name = 'Unknown 71019' where npcid = 71019;
update npc set name = 'Unknown 71020' where npcid = 71020;
update npc set name = 'Unknown 71021' where npcid = 71021;
update npc set name = 'Unknown 71022' where npcid = 71022;
update npc set name = 'Unknown 71023' where npcid = 71023;
update npc set name = 'Garrett' where npcid = 71024;
update npc set name = 'Unknown 71025' where npcid = 71025;
update npc set name = 'Unknown 71026' where npcid = 71026;
update npc set name = 'Unknown 71027' where npcid = 71027;
update npc set name = 'Unknown 71028' where npcid = 71028;
update npc set name = 'Unknown 71029' where npcid = 71029;
update npc set name = 'Healer' where npcid = 71030;
update npc set name = 'Unknown 71031' where npcid = 71031;
update npc set name = 'Unknown 71032' where npcid = 71032;
update npc set name = 'Unknown 71033' where npcid = 71033;
update npc set name = 'Unknown 71034' where npcid = 71034;
update npc set name = 'Unknown 71035' where npcid = 71035;
update npc set name = 'Spirit of Kamyla' where npcid = 71036;
update npc set name = 'Healer' where npcid = 71037;
update npc set name = 'Unknown 71039' where npcid = 71039;
update npc set name = 'Noah' where npcid = 71040;
update npc set name = 'Hoomo' where npcid = 71041;

update npc set name = 'Psuedo Shadow of Flame', nameid = 'Psuedo Shadow of Flame', lawful = -32767 where npcid = 81114;

-- Changed location to fit english text translation..
alter table spawnlist_npc change location location varchar(255) NOT NULL default'';

-- jp char cleanup spawnlist_npc locations
update spawnlist_npc set location = "HV-Novice tele" where npc_templateid = 50004;
update spawnlist_npc set location = "SI-Novice tele" where npc_templateid = 50010;
update spawnlist_npc set location = "SKT-Drist" where npc_templateid = 50055;
update spawnlist_npc set location = "SKT-Matt" where npc_templateid = 50056;
update spawnlist_npc set location = "Windawood-Trey" where npc_templateid = 50054;
update spawnlist_npc set location = "Gludio-Stevie" where npc_templateid = 50024;
update spawnlist_npc set location = "TI-Lucas" where npc_templateid = 50015;
update spawnlist_npc set location = "Kent-Stanley" where npc_templateid = 50020;
update spawnlist_npc set location = "Heine-Riol" where npc_templateid = 50066;
update spawnlist_npc set location = "Aden-Sirius" where npc_templateid = 50044;
update spawnlist_npc set location = "Aden-Elleris" where npc_templateid = 50046;
update spawnlist_npc set location = "Aden-Kinin" where npc_templateid = 50608;
update spawnlist_npc set location = "Oren-Kirius" where npc_templateid = 50051;
update spawnlist_npc set location = "Werldern-Leslie" where npc_templateid = 50039;
update spawnlist_npc set location = "Giran-Wilma" where npc_templateid = 50036;
update spawnlist_npc set location = "Orc Forest-Daniel" where npc_templateid = 50079;
update spawnlist_npc set location = "Gludio-Paul" where npc_templateid = 50080;
update spawnlist_npc set location = "Elven-Ribian" where npc_templateid = 50065;
update spawnlist_npc set location = "HV-Coco" where npc_templateid = 50006;
update spawnlist_npc set location = "HV-Illdrath" where npc_templateid = 50003;
update spawnlist_npc set location = "HV-Barnia" where npc_templateid = 50001;
update spawnlist_npc set location = "SKT-Market Tele outside" where npc_templateid = 50060;
update spawnlist_npc set location = "Gludio-Market Tele outside" where npc_templateid = 50027; 
update spawnlist_npc set location = "Oren-Market Tele outside" where npc_templateid = 50050;
update spawnlist_npc set location = "Giran-Market Tele outside" where npc_templateid = 50034;
update spawnlist_npc set location = "HV,SI-Esmeralda" where npc_templateid = 50007;
update spawnlist_npc set location = "SI-Ishtar" where npc_templateid = 50009;
update spawnlist_npc set location = "FI-Ishiris" where npc_templateid = 50071;
update spawnlist_npc set location = "FI-Lucky" where npc_templateid = 50070;
update spawnlist_npc set location = "SI-Kun" where npc_templateid = 50011;
update spawnlist_npc set location = "Aden-Edlin" where npc_templateid = 50045;
update spawnlist_npc set location = "HV-Karen" where npc_templateid = 50005;
update spawnlist_npc set location = "HV-Enya" where npc_templateid = 50069;
update spawnlist_npc set location = "SC-Deanos" where npc_templateid = 50068;
update spawnlist_npc set location = "SKT-Bunch" where npc_templateid = 50057;
update spawnlist_npc set location = "TI-Keith" where npc_templateid = 50017;
update spawnlist_npc set location = "Gludio-Hooper" where npc_templateid = 50030;
update spawnlist_npc set location = "Kent-Harrison" where npc_templateid = 50022;
update spawnlist_npc set location = "Windawood-Cobb" where npc_templateid = 50053;
update spawnlist_npc set location = "Gludio-Market Tel inside" where npc_templateid = 50026;
update spawnlist_npc set location = "SKT-Market Tele inside" where npc_templateid = 50059;
update spawnlist_npc set location = "Oren-Market Tele inside" where npc_templateid = 50049;
update spawnlist_npc set location = "Giran-Market Tele inside" where npc_templateid = 50033;
update spawnlist_npc set location = "TOI-2F-Ramuda" where npc_templateid = 50043;
update spawnlist_npc set location = "TI-Dungeon-1F-Dilong" where npc_templateid = 50014;
update spawnlist_npc set location = "Assistant Manager of Coliseum" where npc_templateid = 50019;
update spawnlist_npc set location = "SI-Dueling Field Guide" where npc_templateid = 50013;
update spawnlist_npc set location = "HV-Dueling Field Guide" where npc_templateid = 50008;
update spawnlist_npc set location = "SKT-Coliseum Manager" where npc_templateid = 50061;
update spawnlist_npc set location = "Giran-Coliseum Manager" where npc_templateid = 50037;
update spawnlist_npc set location = "Giran-Coliseum Guard" where npc_templateid = 50084;
update spawnlist_npc set location = "TI-Coliseum Manager" where npc_templateid = 50018;
update spawnlist_npc set location = "Gludio-Coliseum Manager" where npc_templateid = 50028;
update spawnlist_npc set location = "SKT-Assistant Manager of Coliseum" where npc_templateid = 50062;
update spawnlist_npc set location = "Giran-Assistant Manager of Coliseum" where npc_templateid = 50038;
update spawnlist_npc set location = "Giran-Assistant Manager of Coliseum" where npc_templateid = 50029;
update spawnlist_npc set location = "Werldern-Coliseum Manager" where npc_templateid = 50041;
update spawnlist_npc set location = "Werldern-Assistant Manager of Coliseum" where npc_templateid = 50042;
update spawnlist_npc set location = "Kent-Inner Castle-Ober" where npc_templateid = 50023;
update spawnlist_npc set location = "Still need to find" where npc_templateid = 50016;
update spawnlist_npc set location = "Kent-Inner Castle Gatekeeper" where npc_templateid = 50021;
update spawnlist_npc set location = "Windawood-Inner Castle Gatekeeper" where npc_templateid = 50052;
update spawnlist_npc set location = "Orc Forest-Fortress Gatekeeper" where npc_templateid = 50063;
update spawnlist_npc set location = "Giran-Inner Castle Gatekeeper" where npc_templateid = 50035;
update spawnlist_npc set location = "Heine-Inner Castle Gatekeeper" where npc_templateid = 50067;
update spawnlist_npc set location = "Iron Gate-Inner Castle Gatekeeper" where npc_templateid = 50040;
update spawnlist_npc set location = "Aden-Inner Castle Gatekeeper" where npc_templateid = 50047;
update spawnlist_npc set location = "Elven-Fairy Princess" where npc_templateid = 70853;
update spawnlist_npc set location = "Dragon Valley 3F-Sepia" where npc_templateid = 50031;
update spawnlist_npc set location = "Kent-Inner Castle-Niki" where npc_templateid = 50118;
update spawnlist_npc set location = "Lastabad Dungeon 1F-Consul" where npc_templateid = 50127;
update spawnlist_npc set location = "Giudin-TZ-Guard" where npc_templateid = 50025;
update spawnlist_npc set location = "Giran-TZ-Guard" where npc_templateid = 50032;
update spawnlist_npc set location = "Oren-TZ-Guard" where npc_templateid = 50048;
update spawnlist_npc set location = "SKT-TZ-Guard" where npc_templateid = 50058;
update spawnlist_npc set location = "Orc Forest-Duvall" where npc_templateid = 50064;
update spawnlist_npc set location = "Oum Dungeon-Teleporter Diarus" where npc_templateid = 50072;
update spawnlist_npc set location = "Diad Fortress-Teleporter Diabes" where npc_templateid = 50073;
update spawnlist_npc set location = "Diad Fortress-Large Cave Teleporter" where npc_templateid = 50074;
update spawnlist_npc set location = "Diad Fortress-Fortress Gatekeeper" where npc_templateid = 50075;










