DELETE FROM commands WHERE name = 'show';
ALTER table commands ADD COLUMN `help_text` TEXT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
REPLACE INTO commands VALUES('appearoffline', '100', 'L1AppearOffline', 'Hides you from the /who command.');
UPDATE commands SET `help_text` = 'Ban a user from chatting for x minutes.' WHERE name = 'chatng';
UPDATE commands SET `help_text` = 'Move a user to a safe place before kicking.' WHERE name = 'skick';
UPDATE commands SET `help_text` = 'Resurrects or heals a specified player or all players on screen.' WHERE name = 'ress';
UPDATE commands SET `help_text` = 'Starts or ends a polymorph event. This will not persist after server restart.' WHERE name = 'polyevent';
UPDATE commands SET `help_text` = 'Give a player or yourself x adena.' WHERE name = 'adena';
UPDATE commands SET `help_text` = 'Enable or disable whether players can drop items on the ground.' WHERE name = 'dropitems';
UPDATE commands SET `help_text` = 'Polymorph yourself or another player.' WHERE name = 'poly';
UPDATE commands SET `help_text` = 'Teleport into a GM room.' WHERE name = 'gmroom';
UPDATE commands SET `help_text` = 'Allows you to see invisible players.' WHERE name = 'findinvis';
UPDATE commands SET `help_text` = 'Put a player in the jail.' WHERE name = 'jail';
UPDATE commands SET `help_text` = 'Give all users within a specific level range a present.' WHERE name = 'lvpresent';
UPDATE commands SET `help_text` = 'Increase your speed.' WHERE name = 'speed';
UPDATE commands SET `help_text` = 'Shut down the server!' WHERE name = 'shutdown';
UPDATE commands SET `help_text` = 'Modify an attribute of yourself or another player.' WHERE name = 'setting';
UPDATE commands SET `help_text` = 'Resolve a specific bug.' WHERE name = 'resolve';
UPDATE commands SET `help_text` = 'Change the ingame weather.' WHERE name = 'weather';
UPDATE commands SET `help_text` = 'Teleport to a specific player.' WHERE name = 'goto';
UPDATE commands SET `help_text` = 'Bring a specific player, or all players, to you.' WHERE name = 'recall';
UPDATE commands SET `help_text` = 'Create any item of any enchant level for yourself.' WHERE name = 'create';
UPDATE commands SET `help_text` = 'Give yourself or another player all buffs.' WHERE name = 'allbuff';
UPDATE commands SET `help_text` = 'Toggle whether you are invisible or not.' WHERE name = 'invis';
UPDATE commands SET `help_text` = 'Kill someone! Mwahahaaha!' WHERE name = 'kill';
UPDATE commands SET `help_text` = 'A list of all commands or help text for a specific command.' WHERE name = 'help';
UPDATE commands SET `help_text` = 'Enable or disable buy/sell of a specific or all shops.' WHERE name = 'toggleshop';
UPDATE commands SET `help_text` = 'Enable or disable global chat.' WHERE name = 'chat';
UPDATE commands SET `help_text` = 'Just displays whatever you type as a system message to yourself.' WHERE name = 'echo';
UPDATE commands SET `help_text` = 'Deletes all items from the ground.' WHERE name = 'cleaning';
UPDATE commands SET `help_text` = 'Gives you all of your classes skills.' WHERE name = 'addskill';
UPDATE commands SET `help_text` = 'Set a player or your own level.' WHERE name = 'level';
UPDATE commands SET `help_text` = 'Improved loc command that gives x and y, as well as map id.' WHERE name = 'loc';
UPDATE commands SET `help_text` = 'A more detailed who command for GMs' WHERE name = 'who';
UPDATE commands SET `help_text` = 'Create an itemset for yourself.' WHERE name = 'itemset';
UPDATE commands SET `help_text` = 'Ban an IP address from playing on the server.' WHERE name = 'banip';
UPDATE commands SET `help_text` = 'Kicks a player out of the game, causing them to have to re-login.' WHERE name = 'kick';
UPDATE commands SET `help_text` = 'Kicks a player while banning their IP address. Their account is NOT banned.' WHERE name = 'powerkick';
UPDATE commands SET `help_text` = 'Teleport yourself somewhere!' WHERE name = 'tele';
UPDATE commands SET `help_text` = 'Find the ID of armor, weapons, etcitems, polymorphs, npcs, or maps.' WHERE name = 'find';
UPDATE commands SET `help_text` = 'Lists basic stats for yourself.' WHERE name = 'desc';
UPDATE commands SET `help_text` = 'Display HP bars above all players, summons, pets, and monsters for yourself only.' WHERE name = 'hpbar';
UPDATE commands SET `help_text` = 'Gives a specific player a present.' WHERE name = 'present';
UPDATE commands SET `help_text` = 'Buffs a specific player, all players, or youself with the buff specified.' WHERE name = 'buff';
UPDATE commands SET `help_text` = 'Run a specific skill animation on yourself.' WHERE name = 'burf';
UPDATE commands SET `help_text` = 'Brings up the patrol window with name, clan, and login datetime of all online players. Double clicking a name will teleport you to them.' WHERE name = 'patrol';
UPDATE commands SET `help_text` = 'Set a specific command as a favourite. Once set, .f will run the saved command.' WHERE name = 'f';
UPDATE commands SET `help_text` = 'Kick and ban a specific player.' WHERE name = 'accbankick';
UPDATE commands SET `help_text` = 'Lists a specific accounts characters and adena.' WHERE name = 'account';
UPDATE commands SET `help_text` = 'Make your character display a specific action sprite.' WHERE name = 'action';
UPDATE commands SET `help_text` = 'Lists a players active buffs and their duration.' WHERE name = 'buffcheck';
UPDATE commands SET `help_text` = 'Starts a specific death match.' WHERE name = 'dm';
UPDATE commands SET `help_text` = 'Brings you to the location a specific bug was reported.' WHERE name = 'gotobug';
UPDATE commands SET `help_text` = 'Runs the daily or monthly tax updates.' WHERE name = 'hometown';
UPDATE commands SET `help_text` = 'Finds the ID for a skill name or the name of a skill ID.' WHERE name = 'findskill';
UPDATE commands SET `help_text` = 'Displays graphics x through y on the ground.' WHERE name = 'gfxid';
UPDATE commands SET `help_text` = 'Displays inventory graphics x through y in your inventory as a candle.' WHERE name = 'invgfxid';
UPDATE commands SET `help_text` = 'Insert a spawnpoint for a specific mob or npc at your location. This is a permanent spawn.' WHERE name = 'insert';
UPDATE commands SET `help_text` = 'Lists a players IP address.' WHERE name = 'ipcheck';
UPDATE commands SET `help_text` = 'Lists what mobs drop a specific item at what % chance.' WHERE name = 'item';
UPDATE commands SET `help_text` = 'Lists what items a mob drops and % chance.' WHERE name = 'mob';
UPDATE commands SET `help_text` = 'Teleports a players entire party to you.' WHERE name = 'partyrecall';
UPDATE commands SET `help_text` = 'Lists the current server rates and allows you to modify/reset them.' WHERE name = 'rates';
UPDATE commands SET `help_text` = 'Refresh your screen.' WHERE name = 'reload';
UPDATE commands SET `help_text` = 'See the description of a reported bug.' WHERE name = 'viewbug';
UPDATE commands SET `help_text` = 'Teleports you to a specified spawn ID.' WHERE name = 'tospawn';
UPDATE commands SET `help_text` = 'Summons a monster or npc at your location.' WHERE name = 'summon';
REPLACE INTO commands VALUES('snoop', '100', 'L1Snoop', 'View a users inventory, storage, elf storage, or pledge storage.');
REPLACE INTO commands VALUES('follow', '100', 'L1Follow', 'Makes your character auto-follow the specified player.');
REPLACE INTO commands VALUES('lazygm', '100', 'L1LazyGm', 'Loops through online players, teleporting you to each of them for x seconds and auto-following them.');
REPLACE INTO commands VALUES('pledge', '100', 'L1Pledge', 'Displays all members in a pledge.');
REPLACE INTO commands VALUES('accountips', '100', 'L1AccountIps', 'Display all IP addresses that have accessed an account and their last login date.');
REPLACE INTO commands VALUES('trace', '100', 'L1Trace', 'Displays all accounts that IP has accessed and when.');