-- IMPORTANT: THIS UPDATE IS NOT YET FINISHED, DONT USE!

-- Queries that are pending an update should be placed here. This allows them
-- to be verified as working together. Once complete, the -pending suffix will
-- be removed.

-- update 64

# Update Dungeon table to better identify location references
ALTER TABLE dungeon ADD src_loc_name varchar(50) default NULL after src_mapid;
ALTER TABLE dungeon DROP COLUMN note;
ALTER TABLE dungeon ADD new_loc_name varchar(50) default NULL after new_mapid;

# Add more stair locations to Lasta entrance 2f - 3f
INSERT into `dungeon` VALUES
(32759,32834,309,'Lastavard Dungeon 3F',32992,32914,308,'Lastavard Dungeon 2F',2),
(32759,32835,309,'Lastavard Dungeon 3F',32992,32914,308,'Lastavard Dungeon 2F',2),
(32759,32837,309,'Lastavard Dungeon 3F',32992,32914,308,'Lastavard Dungeon 2F',2),
(32993,32916,308,'Lastavard Dungeon 2F',32757,32836,309,'Lastavard Dungeon 3F',2),
(32993,32915,308,'Lastavard Dungeon 2F',32757,32836,309,'Lastavard Dungeon 3F',2),
(32994,32913,308,'Lastavard Dungeon 2F',32757,32836,309,'Lastavard Dungeon 3F',2);

# update dungeon location identifiers
update dungeon set src_loc_name = 'Talking Island' where src_mapid = 0;
update dungeon set src_loc_name = 'Talking Island Caves 1F' where src_mapid = 1;
update dungeon set src_loc_name = 'Talking Island Caves 2F' where src_mapid = 2;
update dungeon set src_loc_name = 'Gunter`s Cave' where src_mapid = 3;
update dungeon set src_loc_name = 'Mainland of Aden' where src_mapid = 4;
update dungeon set src_loc_name = 'Traveler`s Ship - Gludio' where src_mapid = 5;
update dungeon set src_loc_name = 'Traveler`s Ship - Talking Island' where src_mapid = 6;
update dungeon set src_loc_name = 'Gludio Dungeon 1F' where src_mapid = 7;
update dungeon set src_loc_name = 'Gludio Dungeon 2F' where src_mapid = 8;
update dungeon set src_loc_name = 'Gludio Dungeon 3F' where src_mapid = 9;
update dungeon set src_loc_name = 'Gludio Dungeon 4F' where src_mapid = 10;
update dungeon set src_loc_name = 'Gludio Dungeon 5F' where src_mapid = 11;
update dungeon set src_loc_name = 'Gludio Dungeon 6F' where src_mapid = 12;
update dungeon set src_loc_name = 'Gludio Dungeon 7F' where src_mapid = 13;
update dungeon set src_loc_name = 'Underground Passage' where src_mapid = 14;
update dungeon set src_loc_name = 'Kent Castle Court' where src_mapid = 15;
update dungeon set src_loc_name = 'Hardin`s Laboratory' where src_mapid = 16;
update dungeon set src_loc_name = 'Nerupa`s Cave' where src_mapid = 17;
update dungeon set src_loc_name = 'Elven Dungeon 1F' where src_mapid = 19;
update dungeon set src_loc_name = 'Elven Dungeon 2F' where src_mapid = 20;
update dungeon set src_loc_name = 'Elven Dungeon 3F' where src_mapid = 21;
update dungeon set src_loc_name = 'Gerard`s Dungeon Test' where src_mapid = 22;
update dungeon set src_loc_name = 'Windawood Castle Dungeon 1F' where src_mapid = 23;
update dungeon set src_loc_name = 'Windawood Castle Dungeon 2F' where src_mapid = 24;
update dungeon set src_loc_name = 'Silver Knight Town Caves 1F' where src_mapid = 25;
update dungeon set src_loc_name = 'Silver Knight Town Caves 2F' where src_mapid = 26;
update dungeon set src_loc_name = 'Silver Knight Town Caves 3F' where src_mapid = 27;
update dungeon set src_loc_name = 'Silver Knight Town Caves 4F' where src_mapid = 28;
update dungeon set src_loc_name = 'Windawood Castle Court' where src_mapid = 29;
update dungeon set src_loc_name = 'Dragon Valley Caves 1F' where src_mapid = 30;
update dungeon set src_loc_name = 'Dragon Valley Caves 2F' where src_mapid = 31;
update dungeon set src_loc_name = 'Dragon Valley Caves 3F' where src_mapid = 32;
update dungeon set src_loc_name = 'Dragon Valley Caves 4F' where src_mapid = 33;
update dungeon set src_loc_name = 'Hall of Honor' where src_mapid = 34;
update dungeon set src_loc_name = 'Dragon Valley Caves 5F' where src_mapid = 35;
update dungeon set src_loc_name = 'Dragon Valley Caves 6F' where src_mapid = 36;
update dungeon set src_loc_name = 'Dragon Valley Caves 7F' where src_mapid = 37;
update dungeon set src_loc_name = 'Ant Caves 8F' where src_mapid = 43;
update dungeon set src_loc_name = 'Ant Caves 6F' where src_mapid = 44;
update dungeon set src_loc_name = 'Ant Caves 2F' where src_mapid = 45;
update dungeon set src_loc_name = 'Ant Caves 3F' where src_mapid = 46;
update dungeon set src_loc_name = 'Ant Caves 1F' where src_mapid = 47;
update dungeon set src_loc_name = 'Ant Caves 4F' where src_mapid = 48;
update dungeon set src_loc_name = 'Ant Caves 5F' where src_mapid = 49;
update dungeon set src_loc_name = 'Ant Caves 7F' where src_mapid = 50;
update dungeon set src_loc_name = 'Ant Caves 9F' where src_mapid = 51;
update dungeon set src_loc_name = 'Giran Castle Court' where src_mapid = 52;
update dungeon set src_loc_name = 'Giran Dungeon 1F' where src_mapid = 53;
update dungeon set src_loc_name = 'Giran Dungeon 2F' where src_mapid = 54;
update dungeon set src_loc_name = 'Giran Dungeon 3F' where src_mapid = 55;
update dungeon set src_loc_name = 'Giran Dungeon 4F' where src_mapid = 56;
update dungeon set src_loc_name = 'Heine Dungeon 1F' where src_mapid = 59;
update dungeon set src_loc_name = 'Heine Dungeon 2F' where src_mapid = 60;
update dungeon set src_loc_name = 'Heine Dungeon 3F' where src_mapid = 61;
update dungeon set src_loc_name = 'Sanctuary of Eva' where src_mapid = 62;
update dungeon set src_loc_name = 'Kingdom of Eva' where src_mapid = 63;
update dungeon set src_loc_name = 'Heine Castle Court' where src_mapid = 64;
update dungeon set src_loc_name = 'Lair of Fafurion' where src_mapid = 65;
update dungeon set src_loc_name = 'Iron Gate Guild Castle' where src_mapid = 66;
update dungeon set src_loc_name = 'Lair of Valakas' where src_mapid = 67;
update dungeon set src_loc_name = 'Forgotten Island' where src_mapid = 70;
update dungeon set src_loc_name = 'Crystal Caverns 1F' where src_mapid = 72;
update dungeon set src_loc_name = 'Crystal Caverns 2F' where src_mapid = 73;
update dungeon set src_loc_name = 'Crystal Caverns 3F' where src_mapid = 74;
update dungeon set src_loc_name = 'Ivory Tower 1F' where src_mapid = 75;
update dungeon set src_loc_name = 'Ivory Tower 2F' where src_mapid = 76;
update dungeon set src_loc_name = 'Ivory Tower 3F' where src_mapid = 77;
update dungeon set src_loc_name = 'Ivory Tower 4F' where src_mapid = 78;
update dungeon set src_loc_name = 'Ivory Tower 5F' where src_mapid = 79;
update dungeon set src_loc_name = 'Ivory Tower 6F' where src_mapid = 80;
update dungeon set src_loc_name = 'Ivory Tower 7F' where src_mapid = 81;
update dungeon set src_loc_name = 'Ivory Tower 8F' where src_mapid = 82;
update dungeon set src_loc_name = 'Traveler`s Ship - Forgotten Island' where src_mapid = 83;
update dungeon set src_loc_name = 'Traveler`s Ship - Heine' where src_mapid = 84;
update dungeon set src_loc_name = 'Singing Island Dungeon' where src_mapid = 85;
update dungeon set src_loc_name = 'Hidden Valley Dungeon' where src_mapid = 86;
update dungeon set src_loc_name = 'Pago`s Room' where src_mapid = 87;
update dungeon set src_loc_name = 'Tower of Insolence 1F' where src_mapid = 101;
update dungeon set src_loc_name = 'Tower of Insolence 2F' where src_mapid = 102;
update dungeon set src_loc_name = 'Tower of Insolence 3F' where src_mapid = 103;
update dungeon set src_loc_name = 'Tower of Insolence 4F' where src_mapid = 104;
update dungeon set src_loc_name = 'Tower of Insolence 5F' where src_mapid = 105;
update dungeon set src_loc_name = 'Tower of Insolence 6F' where src_mapid = 106;
update dungeon set src_loc_name = 'Tower of Insolence 7F' where src_mapid = 107;
update dungeon set src_loc_name = 'Tower of Insolence 8F' where src_mapid = 108;
update dungeon set src_loc_name = 'Tower of Insolence 9F' where src_mapid = 109;
update dungeon set src_loc_name = 'Tower of Insolence 10F' where src_mapid = 110;
update dungeon set src_loc_name = 'Tower of Insolence 11F' where src_mapid = 111;
update dungeon set src_loc_name = 'Tower of Insolence 12F' where src_mapid = 112;
update dungeon set src_loc_name = 'Tower of Insolence 13F' where src_mapid = 113;
update dungeon set src_loc_name = 'Tower of Insolence 14F' where src_mapid = 114;
update dungeon set src_loc_name = 'Tower of Insolence 15F' where src_mapid = 115;
update dungeon set src_loc_name = 'Tower of Insolence 16F' where src_mapid = 116;
update dungeon set src_loc_name = 'Tower of Insolence 17F' where src_mapid = 117;
update dungeon set src_loc_name = 'Tower of Insolence 18F' where src_mapid = 118;
update dungeon set src_loc_name = 'Tower of Insolence 19F' where src_mapid = 119;
update dungeon set src_loc_name = 'Tower of Insolence 20F' where src_mapid = 120;
update dungeon set src_loc_name = 'Tower of Insolence 21F' where src_mapid = 121;
update dungeon set src_loc_name = 'Tower of Insolence 22F' where src_mapid = 122;
update dungeon set src_loc_name = 'Tower of Insolence 23F' where src_mapid = 123;
update dungeon set src_loc_name = 'Tower of Insolence 24F' where src_mapid = 124;
update dungeon set src_loc_name = 'Tower of Insolence 25F' where src_mapid = 125;
update dungeon set src_loc_name = 'Tower of Insolence 26F' where src_mapid = 126;
update dungeon set src_loc_name = 'Tower of Insolence 27F' where src_mapid = 127;
update dungeon set src_loc_name = 'Tower of Insolence 28F' where src_mapid = 128;
update dungeon set src_loc_name = 'Tower of Insolence 29F' where src_mapid = 129;
update dungeon set src_loc_name = 'Tower of Insolence 30F' where src_mapid = 130;
update dungeon set src_loc_name = 'Tower of Insolence 31F' where src_mapid = 131;
update dungeon set src_loc_name = 'Tower of Insolence 32F' where src_mapid = 132;
update dungeon set src_loc_name = 'Tower of Insolence 33F' where src_mapid = 133;
update dungeon set src_loc_name = 'Tower of Insolence 34F' where src_mapid = 134;
update dungeon set src_loc_name = 'Tower of Insolence 35F' where src_mapid = 135;
update dungeon set src_loc_name = 'Tower of Insolence 36F' where src_mapid = 136;
update dungeon set src_loc_name = 'Tower of Insolence 37F' where src_mapid = 137;
update dungeon set src_loc_name = 'Tower of Insolence 38F' where src_mapid = 138;
update dungeon set src_loc_name = 'Tower of Insolence 39F' where src_mapid = 139;
update dungeon set src_loc_name = 'Tower of Insolence 40F' where src_mapid = 140;
update dungeon set src_loc_name = 'Tower of Insolence 41F' where src_mapid = 141;
update dungeon set src_loc_name = 'Tower of Insolence 42F' where src_mapid = 142;
update dungeon set src_loc_name = 'Tower of Insolence 43F' where src_mapid = 143;
update dungeon set src_loc_name = 'Tower of Insolence 44F' where src_mapid = 144;
update dungeon set src_loc_name = 'Tower of Insolence 45F' where src_mapid = 145;
update dungeon set src_loc_name = 'Tower of Insolence 46F' where src_mapid = 146;
update dungeon set src_loc_name = 'Tower of Insolence 47F' where src_mapid = 147;
update dungeon set src_loc_name = 'Tower of Insolence 48F' where src_mapid = 148;
update dungeon set src_loc_name = 'Tower of Insolence 49F' where src_mapid = 149;
update dungeon set src_loc_name = 'Tower of Insolence 50F' where src_mapid = 150;
update dungeon set src_loc_name = 'Tower of Insolence 51F' where src_mapid = 151;
update dungeon set src_loc_name = 'Tower of Insolence 52F' where src_mapid = 152;
update dungeon set src_loc_name = 'Tower of Insolence 53F' where src_mapid = 153;
update dungeon set src_loc_name = 'Tower of Insolence 54F' where src_mapid = 154;
update dungeon set src_loc_name = 'Tower of Insolence 55F' where src_mapid = 155;
update dungeon set src_loc_name = 'Tower of Insolence 56F' where src_mapid = 156;
update dungeon set src_loc_name = 'Tower of Insolence 57F' where src_mapid = 157;
update dungeon set src_loc_name = 'Tower of Insolence 58F' where src_mapid = 158;
update dungeon set src_loc_name = 'Tower of Insolence 59F' where src_mapid = 159;
update dungeon set src_loc_name = 'Tower of Insolence 60F' where src_mapid = 160;
update dungeon set src_loc_name = 'Tower of Insolence 61F' where src_mapid = 161;
update dungeon set src_loc_name = 'Tower of Insolence 62F' where src_mapid = 162;
update dungeon set src_loc_name = 'Tower of Insolence 63F' where src_mapid = 163;
update dungeon set src_loc_name = 'Tower of Insolence 64F' where src_mapid = 164;
update dungeon set src_loc_name = 'Tower of Insolence 65F' where src_mapid = 165;
update dungeon set src_loc_name = 'Tower of Insolence 66F' where src_mapid = 166;
update dungeon set src_loc_name = 'Tower of Insolence 67F' where src_mapid = 167;
update dungeon set src_loc_name = 'Tower of Insolence 68F' where src_mapid = 168;
update dungeon set src_loc_name = 'Tower of Insolence 69F' where src_mapid = 169;
update dungeon set src_loc_name = 'Tower of Insolence 70F' where src_mapid = 170;
update dungeon set src_loc_name = 'Tower of Insolence 71F' where src_mapid = 171;
update dungeon set src_loc_name = 'Tower of Insolence 72F' where src_mapid = 172;
update dungeon set src_loc_name = 'Tower of Insolence 73F' where src_mapid = 173;
update dungeon set src_loc_name = 'Tower of Insolence 74F' where src_mapid = 174;
update dungeon set src_loc_name = 'Tower of Insolence 75F' where src_mapid = 175;
update dungeon set src_loc_name = 'Tower of Insolence 76F' where src_mapid = 176;
update dungeon set src_loc_name = 'Tower of Insolence 77F' where src_mapid = 177;
update dungeon set src_loc_name = 'Tower of Insolence 78F' where src_mapid = 178;
update dungeon set src_loc_name = 'Tower of Insolence 79F' where src_mapid = 179;
update dungeon set src_loc_name = 'Tower of Insolence 80F' where src_mapid = 180;
update dungeon set src_loc_name = 'Tower of Insolence 81F' where src_mapid = 181;
update dungeon set src_loc_name = 'Tower of Insolence 82F' where src_mapid = 182;
update dungeon set src_loc_name = 'Tower of Insolence 83F' where src_mapid = 183;
update dungeon set src_loc_name = 'Tower of Insolence 84F' where src_mapid = 184;
update dungeon set src_loc_name = 'Tower of Insolence 85F' where src_mapid = 185;
update dungeon set src_loc_name = 'Tower of Insolence 86F' where src_mapid = 186;
update dungeon set src_loc_name = 'Tower of Insolence 87F' where src_mapid = 187;
update dungeon set src_loc_name = 'Tower of Insolence 88F' where src_mapid = 188;
update dungeon set src_loc_name = 'Tower of Insolence 89F' where src_mapid = 189;
update dungeon set src_loc_name = 'Tower of Insolence 90F' where src_mapid = 190;
update dungeon set src_loc_name = 'Tower of Insolence 91F' where src_mapid = 191;
update dungeon set src_loc_name = 'Tower of Insolence 92F' where src_mapid = 192;
update dungeon set src_loc_name = 'Tower of Insolence 93F' where src_mapid = 193;
update dungeon set src_loc_name = 'Tower of Insolence 94F' where src_mapid = 194;
update dungeon set src_loc_name = 'Tower of Insolence 95F' where src_mapid = 195;
update dungeon set src_loc_name = 'Tower of Insolence 96F' where src_mapid = 196;
update dungeon set src_loc_name = 'Tower of Insolence 97F' where src_mapid = 197;
update dungeon set src_loc_name = 'Tower of Insolence 98F' where src_mapid = 198;
update dungeon set src_loc_name = 'Tower of Insolence 99F' where src_mapid = 199;
update dungeon set src_loc_name = 'Tower of Insolence 100F' where src_mapid = 200;
update dungeon set src_loc_name = 'Mage Quest Dungeon' where src_mapid = 201;
update dungeon set src_loc_name = 'Jim`s Dungeon' where src_mapid = 237;
update dungeon set src_loc_name = 'Kent Castle Dungeon 1F' where src_mapid = 240;
update dungeon set src_loc_name = 'Kent Castle Dungeon 2F' where src_mapid = 241;
update dungeon set src_loc_name = 'Kent Castle Dungeon 3F' where src_mapid = 242;
update dungeon set src_loc_name = 'Kent Castle Dungeon 4F' where src_mapid = 243;
update dungeon set src_loc_name = 'Polluted Land of Blessing' where src_mapid = 244;
update dungeon set src_loc_name = 'Giran Castle Dungeon 1F' where src_mapid = 248;
update dungeon set src_loc_name = 'Giran Castle Dungeon 2F' where src_mapid = 249;
update dungeon set src_loc_name = 'Giran Castle Dungeon 3F' where src_mapid = 250;
update dungeon set src_loc_name = 'Count Taros` Throne Room' where src_mapid = 251;
update dungeon set src_loc_name = 'Heine Basement Prison' where src_mapid = 252;
update dungeon set src_loc_name = 'Kingdom of Eva' where src_mapid = 253;
update dungeon set src_loc_name = 'Barbados` Hideout' where src_mapid = 254;
update dungeon set src_loc_name = 'IGG Castle Dungeon 1F - Dwarven Mine' where src_mapid = 255;
update dungeon set src_loc_name = 'IGG Castle Dungeon 2F - Wilderness' where src_mapid = 256;
update dungeon set src_loc_name = 'Aden Castle Dungeon 1F - Path of the Dead' where src_mapid = 257;
update dungeon set src_loc_name = 'Aden Castle Dungeon 2F - Grave of the Dead' where src_mapid = 258;
update dungeon set src_loc_name = 'Aden Castle Dungeon 3F - Path of the Dead' where src_mapid = 259;
update dungeon set src_loc_name = 'Aden Castle' where src_mapid = 300;
update dungeon set src_loc_name = 'Aden Sewers' where src_mapid = 301;
update dungeon set src_loc_name = 'Silent Cavern' where src_mapid = 304;
update dungeon set src_loc_name = 'Bludika`s Room' where src_mapid = 305;
update dungeon set src_loc_name = 'Lastavard Dungeon 1F' where src_mapid = 307;
update dungeon set src_loc_name = 'Lastavard Dungeon 2F' where src_mapid = 308;
update dungeon set src_loc_name = 'Lastavard Dungeon 3F' where src_mapid = 309;
update dungeon set src_loc_name = 'Oum Dungeon' where src_mapid = 310;
update dungeon set src_loc_name = 'Diad Fortress' where src_mapid = 320;
update dungeon set src_loc_name = 'Mineral Dungeon' where src_mapid = 330;
update dungeon set src_loc_name = 'Great Cavern' where src_mapid = 400;
update dungeon set src_loc_name = 'Large Cavern Route' where src_mapid = 401;
update dungeon set src_loc_name = 'Sanctuary of Evil' where src_mapid = 410;
update dungeon set src_loc_name = 'Abyss Lake' where src_mapid = 420;
update dungeon set src_loc_name = 'Elemental Grave' where src_mapid = 430;
update dungeon set src_loc_name = 'Pirate Island' where src_mapid = 440;
update dungeon set src_loc_name = 'Pirate Island Dungeon 1F' where src_mapid = 441;
update dungeon set src_loc_name = 'Pirate Island Dungeon 2F' where src_mapid = 442;
update dungeon set src_loc_name = 'Pirate Island Dungeon 3F' where src_mapid = 443;
update dungeon set src_loc_name = 'Pirate Island Dungeon 4F' where src_mapid = 444;
update dungeon set src_loc_name = 'Hidden Dock' where src_mapid = 445;
update dungeon set src_loc_name = 'Traveler`s Ship - Hidden Dock' where src_mapid = 446;
update dungeon set src_loc_name = 'Traveler`s Ship - Pirate Island' where src_mapid = 447;
update dungeon set src_loc_name = 'Front Gate of Lastavard' where src_mapid = 450;
update dungeon set src_loc_name = 'Lastavard - 1F Gathering Room' where src_mapid = 451;
update dungeon set src_loc_name = 'Lastavard - 1F Storm Party Training Room' where src_mapid = 452;
update dungeon set src_loc_name = 'Lastavard - 1F Evil King`s Office' where src_mapid = 453;
update dungeon set src_loc_name = 'Lastavard - 1F Storm Party Training Room A' where src_mapid = 454;
update dungeon set src_loc_name = 'Lastavard - 1F Storm Party Training Room B' where src_mapid = 455;
update dungeon set src_loc_name = 'Lastavard - 1F Evil Summoning Room' where src_mapid = 456;
update dungeon set src_loc_name = 'Lastavard - 1F Sanctuary of Darkness' where src_mapid = 457;
update dungeon set src_loc_name = 'Lastavard - 2F Dark Magic Training Room' where src_mapid = 460;
update dungeon set src_loc_name = 'Lastavard - 2F Dark Magic Research Room' where src_mapid = 461;
update dungeon set src_loc_name = 'Lastavard - 2F Evil Spirit King`s Office' where src_mapid = 462;
update dungeon set src_loc_name = 'Lastavard - 2F Evil Spirit King`s Study' where src_mapid = 463;
update dungeon set src_loc_name = 'Lastavard - 2F Spirit Summoning Room' where src_mapid = 464;
update dungeon set src_loc_name = 'Lastavard - 2F Spirit Habitat' where src_mapid = 465;
update dungeon set src_loc_name = 'Lastavard - 2F Black Spirit Research Room' where src_mapid = 466;
update dungeon set src_loc_name = 'Lastavard - 2F Sanctuary of Oblivion A' where src_mapid = 467;
update dungeon set src_loc_name = 'Lastavard - 2F Sanctuary of Oblivion B' where src_mapid = 468;
update dungeon set src_loc_name = 'Lastavard - 3F Evil Spirit Altar' where src_mapid = 470;
update dungeon set src_loc_name = 'Lastavard - 3F Devil Lord Altar' where src_mapid = 471;
update dungeon set src_loc_name = 'Lastavard - 3F Mercenary Training Room' where src_mapid = 472;
update dungeon set src_loc_name = 'Lastavard - 3F Inquisitor`s Training Room' where src_mapid = 473;
update dungeon set src_loc_name = 'Lastavard - 3F Oum Testing Room' where src_mapid = 474;
update dungeon set src_loc_name = 'Lastavard - 3F Inquisitor King`s Office' where src_mapid = 475;
update dungeon set src_loc_name = 'Lastavard - 3F Central Control Room' where src_mapid = 476;
update dungeon set src_loc_name = 'Lastavard - 3F Devil Lord Mercenary Room' where src_mapid = 477;
update dungeon set src_loc_name = 'Lastavard - 3F Control Zone' where src_mapid = 478;
update dungeon set src_loc_name = 'Pirate`s Isle' where src_mapid = 480;
update dungeon set src_loc_name = 'Pirate Island - Kamyla`s Room' where src_mapid = 481;
update dungeon set src_loc_name = 'Lastavard - Basement Training Room' where src_mapid = 490;
update dungeon set src_loc_name = 'Lastavard - Basement Passageway' where src_mapid = 491;
update dungeon set src_loc_name = 'Lastavard - Basement Control Room' where src_mapid = 493;
update dungeon set src_loc_name = 'Lastavard - Basement Battle Arena' where src_mapid = 495;
update dungeon set src_loc_name = 'Outer Area of Temple of Shadows' where src_mapid = 521;
update dungeon set src_loc_name = 'Lastavard - 4F Temple of Gran Kain / Kenya' where src_mapid = 530;
update dungeon set src_loc_name = 'Lastavard - 4F Viatas / Baromes / Endias' where src_mapid = 531;
update dungeon set src_loc_name = 'Lastavard - 4F Gardens / Edea' where src_mapid = 532;
update dungeon set src_loc_name = 'Lastavard - 4F Tiames / Ramias / Barode' where src_mapid = 533;
update dungeon set src_loc_name = 'Lastavard - 4F Cassandra / Dante' where src_mapid = 534;
update dungeon set src_loc_name = 'Lastavard - 3F Sanctuary of Oblivion' where src_mapid = 536;
update dungeon set src_loc_name = 'Grave of Ships - Outland' where src_mapid = 550;
update dungeon set src_loc_name = 'Grave of Ships - 1F-1' where src_mapid = 551;
update dungeon set src_loc_name = 'Grave of Ships - 1F-2' where src_mapid = 552;
update dungeon set src_loc_name = 'Grave of Ships - 1F-3' where src_mapid = 553;
update dungeon set src_loc_name = 'Grave of Ships - 2F-1' where src_mapid = 554;
update dungeon set src_loc_name = 'Grave of Ships - 2F-2' where src_mapid = 555;
update dungeon set src_loc_name = 'Grave of Ships - 2F-3' where src_mapid = 556;
update dungeon set src_loc_name = 'Grave of Ships - 3F' where src_mapid = 557;
update dungeon set src_loc_name = 'Grave of Ships - Deep Sea Floor' where src_mapid = 558;
update dungeon set src_loc_name = 'Cave of Desire - Outland' where src_mapid = 600;
update dungeon set src_loc_name = 'Cave of Desire - Lobby' where src_mapid = 601;
update dungeon set src_loc_name = 'Fallen Cave' where src_mapid = 778;
update dungeon set src_loc_name = 'Fallen Cave Underwater' where src_mapid = 779;
update dungeon set src_loc_name = '' where src_mapid = 780;
update dungeon set src_loc_name = '' where src_mapid = 781;
update dungeon set src_loc_name = '' where src_mapid = 1000;
update dungeon set src_loc_name = '' where src_mapid = 1001;
update dungeon set src_loc_name = '' where src_mapid = 1005;
update dungeon set src_loc_name = 'Ancient Space 1F' where src_mapid = 2000;
update dungeon set src_loc_name = 'Ancient Space 3F' where src_mapid = 2002;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 1' where src_mapid = 5068;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 2' where src_mapid = 5069;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 3' where src_mapid = 5070;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 4' where src_mapid = 5071;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 5' where src_mapid = 5072;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 6' where src_mapid = 5073;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 7' where src_mapid = 5074;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 8' where src_mapid = 5075;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 9' where src_mapid = 5076;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 10' where src_mapid = 5077;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 11' where src_mapid = 5078;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 12' where src_mapid = 5079;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 13' where src_mapid = 5080;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 14' where src_mapid = 5081;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 15' where src_mapid = 5082;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 16' where src_mapid = 5083;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 17' where src_mapid = 5084;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 18' where src_mapid = 5085;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 19' where src_mapid = 5086;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 20' where src_mapid = 5087;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 21' where src_mapid = 5088;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 22' where src_mapid = 5089;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 23' where src_mapid = 5090;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 24' where src_mapid = 5091;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 25' where src_mapid = 5092;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 26' where src_mapid = 5093;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 27' where src_mapid = 5094;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 28' where src_mapid = 5095;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 29' where src_mapid = 5096;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 30' where src_mapid = 5097;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 31' where src_mapid = 5098;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 32' where src_mapid = 5099;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 33' where src_mapid = 5100;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 34' where src_mapid = 5101;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 35' where src_mapid = 5102;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 36' where src_mapid = 5103;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 37' where src_mapid = 5104;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 38' where src_mapid = 5105;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 39' where src_mapid = 5106;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 40' where src_mapid = 5107;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 41' where src_mapid = 5108;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 42' where src_mapid = 5109;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 43' where src_mapid = 5110;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 44' where src_mapid = 5111;
update dungeon set src_loc_name = 'Giran Pledge Conference Hall 45' where src_mapid = 5112;
update dungeon set src_loc_name = 'Heine Underground House 1' where src_mapid = 5113;
update dungeon set src_loc_name = 'Heine Underground House 2' where src_mapid = 5114;
update dungeon set src_loc_name = 'Heine Underground House 3' where src_mapid = 5115;
update dungeon set src_loc_name = 'Heine Underground House 4' where src_mapid = 5116;
update dungeon set src_loc_name = 'Heine Underground House 5' where src_mapid = 5117;
update dungeon set src_loc_name = 'Heine Underground House 6' where src_mapid = 5118;
update dungeon set src_loc_name = 'Heine Underground House 7' where src_mapid = 5119;
update dungeon set src_loc_name = 'Heine Underground House 8' where src_mapid = 5120;
update dungeon set src_loc_name = 'Heine Underground House 9' where src_mapid = 5121;
update dungeon set src_loc_name = 'Heine Underground House 10' where src_mapid = 5122;
update dungeon set src_loc_name = 'Heine Underground House 11' where src_mapid = 5123;
update dungeon set src_loc_name = 'InnRoom - Talking Island' where src_mapid = 16384;
update dungeon set src_loc_name = 'Conference Hall - Talking Island' where src_mapid = 16896;
update dungeon set src_loc_name = 'InnRoom - Gludio' where src_mapid = 17408;
update dungeon set src_loc_name = 'Conference Hall - Gludio' where src_mapid = 17920;
update dungeon set src_loc_name = 'InnRoom - Giran' where src_mapid = 18432;
update dungeon set src_loc_name = 'Conference Hall - Giran' where src_mapid = 18944;
update dungeon set src_loc_name = 'InnRoom - Oren' where src_mapid = 19456;
update dungeon set src_loc_name = 'Conference Hall - Oren' where src_mapid = 19968;
update dungeon set src_loc_name = 'InnRoom - Windawood' where src_mapid = 20480;
update dungeon set src_loc_name = 'Conference Hall - Windawood' where src_mapid = 20992;
update dungeon set src_loc_name = 'InnRoom - Silver Knight Town' where src_mapid = 21504;
update dungeon set src_loc_name = 'Conference Hall - Silver Knight Town' where src_mapid = 22016;
update dungeon set src_loc_name = 'InnRoom - Heine' where src_mapid = 22528;
update dungeon set src_loc_name = 'Conference Hall - Heine' where src_mapid = 23040;
update dungeon set src_loc_name = 'InnRoom' where src_mapid = 23552;
update dungeon set src_loc_name = 'Conference Hall -' where src_mapid = 24064;
update dungeon set src_loc_name = 'InnRoom' where src_mapid = 24576;
update dungeon set src_loc_name = 'Conference Hall -' where src_mapid = 25088;
update dungeon set src_loc_name = 'InnRoom' where src_mapid = 20992;
update dungeon set src_loc_name = 'InnRoom' where src_mapid = 21504;
update dungeon set src_loc_name = 'InnRoom' where src_mapid = 22016;
update dungeon set src_loc_name = 'InnRoom' where src_mapid = 22528;
update dungeon set src_loc_name = 'InnRoom' where src_mapid = 23040;
update dungeon set src_loc_name = 'InnRoom' where src_mapid = 23552;
update dungeon set src_loc_name = 'InnRoom' where src_mapid = 24064;
update dungeon set src_loc_name = 'InnRoom' where src_mapid = 24576;
update dungeon set src_loc_name = 'InnRoom' where src_mapid = 25088;
update dungeon set new_loc_name = 'Talking Island' where new_mapid = 0;
update dungeon set new_loc_name = 'Talking Island Caves 1F' where new_mapid = 1;
update dungeon set new_loc_name = 'Talking Island Caves 2F' where new_mapid = 2;
update dungeon set new_loc_name = 'Gunter`s Cave' where new_mapid = 3;
update dungeon set new_loc_name = 'Mainland of Aden' where new_mapid = 4;
update dungeon set new_loc_name = 'Traveler`s Ship - Gludio' where new_mapid = 5;
update dungeon set new_loc_name = 'Traveler`s Ship - Talking Island' where new_mapid = 6;
update dungeon set new_loc_name = 'Gludio Dungeon 1F' where new_mapid = 7;
update dungeon set new_loc_name = 'Gludio Dungeon 2F' where new_mapid = 8;
update dungeon set new_loc_name = 'Gludio Dungeon 3F' where new_mapid = 9;
update dungeon set new_loc_name = 'Gludio Dungeon 4F' where new_mapid = 10;
update dungeon set new_loc_name = 'Gludio Dungeon 5F' where new_mapid = 11;
update dungeon set new_loc_name = 'Gludio Dungeon 6F' where new_mapid = 12;
update dungeon set new_loc_name = 'Gludio Dungeon 7F' where new_mapid = 13;
update dungeon set new_loc_name = 'Underground Passage' where new_mapid = 14;
update dungeon set new_loc_name = 'Kent Castle Court' where new_mapid = 15;
update dungeon set new_loc_name = 'Hardin`s Laboratory' where new_mapid = 16;
update dungeon set new_loc_name = 'Nerupa`s Cave' where new_mapid = 17;
update dungeon set new_loc_name = 'Elven Dungeon 1F' where new_mapid = 19;
update dungeon set new_loc_name = 'Elven Dungeon 2F' where new_mapid = 20;
update dungeon set new_loc_name = 'Elven Dungeon 3F' where new_mapid = 21;
update dungeon set new_loc_name = 'Gerard`s Dungeon Test' where new_mapid = 22;
update dungeon set new_loc_name = 'Windawood Castle Dungeon 1F' where new_mapid = 23;
update dungeon set new_loc_name = 'Windawood Castle Dungeon 2F' where new_mapid = 24;
update dungeon set new_loc_name = 'Silver Knight Town Caves 1F' where new_mapid = 25;
update dungeon set new_loc_name = 'Silver Knight Town Caves 2F' where new_mapid = 26;
update dungeon set new_loc_name = 'Silver Knight Town Caves 3F' where new_mapid = 27;
update dungeon set new_loc_name = 'Silver Knight Town Caves 4F' where new_mapid = 28;
update dungeon set new_loc_name = 'Windawood Castle Court' where new_mapid = 29;
update dungeon set new_loc_name = 'Dragon Valley Caves 1F' where new_mapid = 30;
update dungeon set new_loc_name = 'Dragon Valley Caves 2F' where new_mapid = 31;
update dungeon set new_loc_name = 'Dragon Valley Caves 3F' where new_mapid = 32;
update dungeon set new_loc_name = 'Dragon Valley Caves 4F' where new_mapid = 33;
update dungeon set new_loc_name = 'Hall of Honor' where new_mapid = 34;
update dungeon set new_loc_name = 'Dragon Valley Caves 5F' where new_mapid = 35;
update dungeon set new_loc_name = 'Dragon Valley Caves 6F' where new_mapid = 36;
update dungeon set new_loc_name = 'Dragon Valley Caves 7F' where new_mapid = 37;
update dungeon set new_loc_name = 'Ant Caves 8F' where new_mapid = 43;
update dungeon set new_loc_name = 'Ant Caves 6F' where new_mapid = 44;
update dungeon set new_loc_name = 'Ant Caves 2F' where new_mapid = 45;
update dungeon set new_loc_name = 'Ant Caves 3F' where new_mapid = 46;
update dungeon set new_loc_name = 'Ant Caves 1F' where new_mapid = 47;
update dungeon set new_loc_name = 'Ant Caves 4F' where new_mapid = 48;
update dungeon set new_loc_name = 'Ant Caves 5F' where new_mapid = 49;
update dungeon set new_loc_name = 'Ant Caves 7F' where new_mapid = 50;
update dungeon set new_loc_name = 'Ant Caves 9F' where new_mapid = 51;
update dungeon set new_loc_name = 'Giran Castle Court' where new_mapid = 52;
update dungeon set new_loc_name = 'Giran Dungeon 1F' where new_mapid = 53;
update dungeon set new_loc_name = 'Giran Dungeon 2F' where new_mapid = 54;
update dungeon set new_loc_name = 'Giran Dungeon 3F' where new_mapid = 55;
update dungeon set new_loc_name = 'Giran Dungeon 4F' where new_mapid = 56;
update dungeon set new_loc_name = 'Heine Dungeon 1F' where new_mapid = 59;
update dungeon set new_loc_name = 'Heine Dungeon 2F' where new_mapid = 60;
update dungeon set new_loc_name = 'Heine Dungeon 3F' where new_mapid = 61;
update dungeon set new_loc_name = 'Sanctuary of Eva' where new_mapid = 62;
update dungeon set new_loc_name = 'Kingdom of Eva' where new_mapid = 63;
update dungeon set new_loc_name = 'Heine Castle Court' where new_mapid = 64;
update dungeon set new_loc_name = 'Lair of Fafurion' where new_mapid = 65;
update dungeon set new_loc_name = 'Iron Gate Guild Castle' where new_mapid = 66;
update dungeon set new_loc_name = 'Lair of Valakas' where new_mapid = 67;
update dungeon set new_loc_name = 'Forgotten Island' where new_mapid = 70;
update dungeon set new_loc_name = 'Crystal Caverns 1F' where new_mapid = 72;
update dungeon set new_loc_name = 'Crystal Caverns 2F' where new_mapid = 73;
update dungeon set new_loc_name = 'Crystal Caverns 3F' where new_mapid = 74;
update dungeon set new_loc_name = 'Ivory Tower 1F' where new_mapid = 75;
update dungeon set new_loc_name = 'Ivory Tower 2F' where new_mapid = 76;
update dungeon set new_loc_name = 'Ivory Tower 3F' where new_mapid = 77;
update dungeon set new_loc_name = 'Ivory Tower 4F' where new_mapid = 78;
update dungeon set new_loc_name = 'Ivory Tower 5F' where new_mapid = 79;
update dungeon set new_loc_name = 'Ivory Tower 6F' where new_mapid = 80;
update dungeon set new_loc_name = 'Ivory Tower 7F' where new_mapid = 81;
update dungeon set new_loc_name = 'Ivory Tower 8F' where new_mapid = 82;
update dungeon set new_loc_name = 'Traveler`s Ship - Forgotten Island' where new_mapid = 83;
update dungeon set new_loc_name = 'Traveler`s Ship - Heine' where new_mapid = 84;
update dungeon set new_loc_name = 'Singing Island Dungeon' where new_mapid = 85;
update dungeon set new_loc_name = 'Hidden Valley Dungeon' where new_mapid = 86;
update dungeon set new_loc_name = 'Pago`s Room' where new_mapid = 87;
update dungeon set new_loc_name = 'Tower of Insolence 1F' where new_mapid = 101;
update dungeon set new_loc_name = 'Tower of Insolence 2F' where new_mapid = 102;
update dungeon set new_loc_name = 'Tower of Insolence 3F' where new_mapid = 103;
update dungeon set new_loc_name = 'Tower of Insolence 4F' where new_mapid = 104;
update dungeon set new_loc_name = 'Tower of Insolence 5F' where new_mapid = 105;
update dungeon set new_loc_name = 'Tower of Insolence 6F' where new_mapid = 106;
update dungeon set new_loc_name = 'Tower of Insolence 7F' where new_mapid = 107;
update dungeon set new_loc_name = 'Tower of Insolence 8F' where new_mapid = 108;
update dungeon set new_loc_name = 'Tower of Insolence 9F' where new_mapid = 109;
update dungeon set new_loc_name = 'Tower of Insolence 10F' where new_mapid = 110;
update dungeon set new_loc_name = 'Tower of Insolence 11F' where new_mapid = 111;
update dungeon set new_loc_name = 'Tower of Insolence 12F' where new_mapid = 112;
update dungeon set new_loc_name = 'Tower of Insolence 13F' where new_mapid = 113;
update dungeon set new_loc_name = 'Tower of Insolence 14F' where new_mapid = 114;
update dungeon set new_loc_name = 'Tower of Insolence 15F' where new_mapid = 115;
update dungeon set new_loc_name = 'Tower of Insolence 16F' where new_mapid = 116;
update dungeon set new_loc_name = 'Tower of Insolence 17F' where new_mapid = 117;
update dungeon set new_loc_name = 'Tower of Insolence 18F' where new_mapid = 118;
update dungeon set new_loc_name = 'Tower of Insolence 19F' where new_mapid = 119;
update dungeon set new_loc_name = 'Tower of Insolence 20F' where new_mapid = 120;
update dungeon set new_loc_name = 'Tower of Insolence 21F' where new_mapid = 121;
update dungeon set new_loc_name = 'Tower of Insolence 22F' where new_mapid = 122;
update dungeon set new_loc_name = 'Tower of Insolence 23F' where new_mapid = 123;
update dungeon set new_loc_name = 'Tower of Insolence 24F' where new_mapid = 124;
update dungeon set new_loc_name = 'Tower of Insolence 25F' where new_mapid = 125;
update dungeon set new_loc_name = 'Tower of Insolence 26F' where new_mapid = 126;
update dungeon set new_loc_name = 'Tower of Insolence 27F' where new_mapid = 127;
update dungeon set new_loc_name = 'Tower of Insolence 28F' where new_mapid = 128;
update dungeon set new_loc_name = 'Tower of Insolence 29F' where new_mapid = 129;
update dungeon set new_loc_name = 'Tower of Insolence 30F' where new_mapid = 130;
update dungeon set new_loc_name = 'Tower of Insolence 31F' where new_mapid = 131;
update dungeon set new_loc_name = 'Tower of Insolence 32F' where new_mapid = 132;
update dungeon set new_loc_name = 'Tower of Insolence 33F' where new_mapid = 133;
update dungeon set new_loc_name = 'Tower of Insolence 34F' where new_mapid = 134;
update dungeon set new_loc_name = 'Tower of Insolence 35F' where new_mapid = 135;
update dungeon set new_loc_name = 'Tower of Insolence 36F' where new_mapid = 136;
update dungeon set new_loc_name = 'Tower of Insolence 37F' where new_mapid = 137;
update dungeon set new_loc_name = 'Tower of Insolence 38F' where new_mapid = 138;
update dungeon set new_loc_name = 'Tower of Insolence 39F' where new_mapid = 139;
update dungeon set new_loc_name = 'Tower of Insolence 40F' where new_mapid = 140;
update dungeon set new_loc_name = 'Tower of Insolence 41F' where new_mapid = 141;
update dungeon set new_loc_name = 'Tower of Insolence 42F' where new_mapid = 142;
update dungeon set new_loc_name = 'Tower of Insolence 43F' where new_mapid = 143;
update dungeon set new_loc_name = 'Tower of Insolence 44F' where new_mapid = 144;
update dungeon set new_loc_name = 'Tower of Insolence 45F' where new_mapid = 145;
update dungeon set new_loc_name = 'Tower of Insolence 46F' where new_mapid = 146;
update dungeon set new_loc_name = 'Tower of Insolence 47F' where new_mapid = 147;
update dungeon set new_loc_name = 'Tower of Insolence 48F' where new_mapid = 148;
update dungeon set new_loc_name = 'Tower of Insolence 49F' where new_mapid = 149;
update dungeon set new_loc_name = 'Tower of Insolence 50F' where new_mapid = 150;
update dungeon set new_loc_name = 'Tower of Insolence 51F' where new_mapid = 151;
update dungeon set new_loc_name = 'Tower of Insolence 52F' where new_mapid = 152;
update dungeon set new_loc_name = 'Tower of Insolence 53F' where new_mapid = 153;
update dungeon set new_loc_name = 'Tower of Insolence 54F' where new_mapid = 154;
update dungeon set new_loc_name = 'Tower of Insolence 55F' where new_mapid = 155;
update dungeon set new_loc_name = 'Tower of Insolence 56F' where new_mapid = 156;
update dungeon set new_loc_name = 'Tower of Insolence 57F' where new_mapid = 157;
update dungeon set new_loc_name = 'Tower of Insolence 58F' where new_mapid = 158;
update dungeon set new_loc_name = 'Tower of Insolence 59F' where new_mapid = 159;
update dungeon set new_loc_name = 'Tower of Insolence 60F' where new_mapid = 160;
update dungeon set new_loc_name = 'Tower of Insolence 61F' where new_mapid = 161;
update dungeon set new_loc_name = 'Tower of Insolence 62F' where new_mapid = 162;
update dungeon set new_loc_name = 'Tower of Insolence 63F' where new_mapid = 163;
update dungeon set new_loc_name = 'Tower of Insolence 64F' where new_mapid = 164;
update dungeon set new_loc_name = 'Tower of Insolence 65F' where new_mapid = 165;
update dungeon set new_loc_name = 'Tower of Insolence 66F' where new_mapid = 166;
update dungeon set new_loc_name = 'Tower of Insolence 67F' where new_mapid = 167;
update dungeon set new_loc_name = 'Tower of Insolence 68F' where new_mapid = 168;
update dungeon set new_loc_name = 'Tower of Insolence 69F' where new_mapid = 169;
update dungeon set new_loc_name = 'Tower of Insolence 70F' where new_mapid = 170;
update dungeon set new_loc_name = 'Tower of Insolence 71F' where new_mapid = 171;
update dungeon set new_loc_name = 'Tower of Insolence 72F' where new_mapid = 172;
update dungeon set new_loc_name = 'Tower of Insolence 73F' where new_mapid = 173;
update dungeon set new_loc_name = 'Tower of Insolence 74F' where new_mapid = 174;
update dungeon set new_loc_name = 'Tower of Insolence 75F' where new_mapid = 175;
update dungeon set new_loc_name = 'Tower of Insolence 76F' where new_mapid = 176;
update dungeon set new_loc_name = 'Tower of Insolence 77F' where new_mapid = 177;
update dungeon set new_loc_name = 'Tower of Insolence 78F' where new_mapid = 178;
update dungeon set new_loc_name = 'Tower of Insolence 79F' where new_mapid = 179;
update dungeon set new_loc_name = 'Tower of Insolence 80F' where new_mapid = 180;
update dungeon set new_loc_name = 'Tower of Insolence 81F' where new_mapid = 181;
update dungeon set new_loc_name = 'Tower of Insolence 82F' where new_mapid = 182;
update dungeon set new_loc_name = 'Tower of Insolence 83F' where new_mapid = 183;
update dungeon set new_loc_name = 'Tower of Insolence 84F' where new_mapid = 184;
update dungeon set new_loc_name = 'Tower of Insolence 85F' where new_mapid = 185;
update dungeon set new_loc_name = 'Tower of Insolence 86F' where new_mapid = 186;
update dungeon set new_loc_name = 'Tower of Insolence 87F' where new_mapid = 187;
update dungeon set new_loc_name = 'Tower of Insolence 88F' where new_mapid = 188;
update dungeon set new_loc_name = 'Tower of Insolence 89F' where new_mapid = 189;
update dungeon set new_loc_name = 'Tower of Insolence 90F' where new_mapid = 190;
update dungeon set new_loc_name = 'Tower of Insolence 91F' where new_mapid = 191;
update dungeon set new_loc_name = 'Tower of Insolence 92F' where new_mapid = 192;
update dungeon set new_loc_name = 'Tower of Insolence 93F' where new_mapid = 193;
update dungeon set new_loc_name = 'Tower of Insolence 94F' where new_mapid = 194;
update dungeon set new_loc_name = 'Tower of Insolence 95F' where new_mapid = 195;
update dungeon set new_loc_name = 'Tower of Insolence 96F' where new_mapid = 196;
update dungeon set new_loc_name = 'Tower of Insolence 97F' where new_mapid = 197;
update dungeon set new_loc_name = 'Tower of Insolence 98F' where new_mapid = 198;
update dungeon set new_loc_name = 'Tower of Insolence 99F' where new_mapid = 199;
update dungeon set new_loc_name = 'Tower of Insolence 100F' where new_mapid = 200;
update dungeon set new_loc_name = 'Mage Quest Dungeon' where new_mapid = 201;
update dungeon set new_loc_name = 'Jim`s Dungeon' where new_mapid = 237;
update dungeon set new_loc_name = 'Kent Castle Dungeon 1F' where new_mapid = 240;
update dungeon set new_loc_name = 'Kent Castle Dungeon 2F' where new_mapid = 241;
update dungeon set new_loc_name = 'Kent Castle Dungeon 3F' where new_mapid = 242;
update dungeon set new_loc_name = 'Kent Castle Dungeon 4F' where new_mapid = 243;
update dungeon set new_loc_name = 'Polluted Land of Blessing' where new_mapid = 244;
update dungeon set new_loc_name = 'Giran Castle Dungeon 1F' where new_mapid = 248;
update dungeon set new_loc_name = 'Giran Castle Dungeon 2F' where new_mapid = 249;
update dungeon set new_loc_name = 'Giran Castle Dungeon 3F' where new_mapid = 250;
update dungeon set new_loc_name = 'Count Taros` Throne Room' where new_mapid = 251;
update dungeon set new_loc_name = 'Heine Basement Prison' where new_mapid = 252;
update dungeon set new_loc_name = 'Kingdom of Eva' where new_mapid = 253;
update dungeon set new_loc_name = 'Barbados` Hideout' where new_mapid = 254;
update dungeon set new_loc_name = 'IGG Castle Dungeon 1F - Dwarven Mine' where new_mapid = 255;
update dungeon set new_loc_name = 'IGG Castle Dungeon 2F - Wilderness' where new_mapid = 256;
update dungeon set new_loc_name = 'Aden Castle Dungeon 1F - Path of the Dead' where new_mapid = 257;
update dungeon set new_loc_name = 'Aden Castle Dungeon 2F - Grave of the Dead' where new_mapid = 258;
update dungeon set new_loc_name = 'Aden Castle Dungeon 3F - Path of the Dead' where new_mapid = 259;
update dungeon set new_loc_name = 'Aden Castle' where new_mapid = 300;
update dungeon set new_loc_name = 'Aden Sewers' where new_mapid = 301;
update dungeon set new_loc_name = 'Silent Cavern' where new_mapid = 304;
update dungeon set new_loc_name = 'Bludika`s Room' where new_mapid = 305;
update dungeon set new_loc_name = 'Lastavard Dungeon 1F' where new_mapid = 307;
update dungeon set new_loc_name = 'Lastavard Dungeon 2F' where new_mapid = 308;
update dungeon set new_loc_name = 'Lastavard Dungeon 3F' where new_mapid = 309;
update dungeon set new_loc_name = 'Oum Dungeon' where new_mapid = 310;
update dungeon set new_loc_name = 'Diad Fortress' where new_mapid = 320;
update dungeon set new_loc_name = 'Mineral Dungeon' where new_mapid = 330;
update dungeon set new_loc_name = 'Great Cavern' where new_mapid = 400;
update dungeon set new_loc_name = 'Large Cavern Route' where new_mapid = 401;
update dungeon set new_loc_name = 'Sanctuary of Evil' where new_mapid = 410;
update dungeon set new_loc_name = 'Abyss Lake' where new_mapid = 420;
update dungeon set new_loc_name = 'Elemental Grave' where new_mapid = 430;
update dungeon set new_loc_name = 'Pirate Island' where new_mapid = 440;
update dungeon set new_loc_name = 'Pirate Island Dungeon 1F' where new_mapid = 441;
update dungeon set new_loc_name = 'Pirate Island Dungeon 2F' where new_mapid = 442;
update dungeon set new_loc_name = 'Pirate Island Dungeon 3F' where new_mapid = 443;
update dungeon set new_loc_name = 'Pirate Island Dungeon 4F' where new_mapid = 444;
update dungeon set new_loc_name = 'Hidden Dock' where new_mapid = 445;
update dungeon set new_loc_name = 'Traveler`s Ship - Hidden Dock' where new_mapid = 446;
update dungeon set new_loc_name = 'Traveler`s Ship - Pirate Island' where new_mapid = 447;
update dungeon set new_loc_name = 'Front Gate of Lastavard' where new_mapid = 450;
update dungeon set new_loc_name = 'Lastavard - 1F Gathering Room' where new_mapid = 451;
update dungeon set new_loc_name = 'Lastavard - 1F Storm Party Training Room' where new_mapid = 452;
update dungeon set new_loc_name = 'Lastavard - 1F Evil King`s Office' where new_mapid = 453;
update dungeon set new_loc_name = 'Lastavard - 1F Storm Party Training Room A' where new_mapid = 454;
update dungeon set new_loc_name = 'Lastavard - 1F Storm Party Training Room B' where new_mapid = 455;
update dungeon set new_loc_name = 'Lastavard - 1F Evil Summoning Room' where new_mapid = 456;
update dungeon set new_loc_name = 'Lastavard - 1F Sanctuary of Darkness' where new_mapid = 457;
update dungeon set new_loc_name = 'Lastavard - 2F Dark Magic Training Room' where new_mapid = 460;
update dungeon set new_loc_name = 'Lastavard - 2F Dark Magic Research Room' where new_mapid = 461;
update dungeon set new_loc_name = 'Lastavard - 2F Evil Spirit King`s Office' where new_mapid = 462;
update dungeon set new_loc_name = 'Lastavard - 2F Evil Spirit King`s Study' where new_mapid = 463;
update dungeon set new_loc_name = 'Lastavard - 2F Spirit Summoning Room' where new_mapid = 464;
update dungeon set new_loc_name = 'Lastavard - 2F Spirit Habitat' where new_mapid = 465;
update dungeon set new_loc_name = 'Lastavard - 2F Black Spirit Research Room' where new_mapid = 466;
update dungeon set new_loc_name = 'Lastavard - 2F Sanctuary of Oblivion A' where new_mapid = 467;
update dungeon set new_loc_name = 'Lastavard - 2F Sanctuary of Oblivion B' where new_mapid = 468;
update dungeon set new_loc_name = 'Lastavard - 3F Evil Spirit Altar' where new_mapid = 470;
update dungeon set new_loc_name = 'Lastavard - 3F Devil Lord Altar' where new_mapid = 471;
update dungeon set new_loc_name = 'Lastavard - 3F Mercenary Training Room' where new_mapid = 472;
update dungeon set new_loc_name = 'Lastavard - 3F Inquisitor`s Training Room' where new_mapid = 473;
update dungeon set new_loc_name = 'Lastavard - 3F Oum Testing Room' where new_mapid = 474;
update dungeon set new_loc_name = 'Lastavard - 3F Inquisitor King`s Office' where new_mapid = 475;
update dungeon set new_loc_name = 'Lastavard - 3F Central Control Room' where new_mapid = 476;
update dungeon set new_loc_name = 'Lastavard - 3F Devil Lord Mercenary Room' where new_mapid = 477;
update dungeon set new_loc_name = 'Lastavard - 3F Control Zone' where new_mapid = 478;
update dungeon set new_loc_name = 'Pirate`s Isle' where new_mapid = 480;
update dungeon set new_loc_name = 'Pirate Island - Kamyla`s Room' where new_mapid = 481;
update dungeon set new_loc_name = 'Lastavard - Basement Training Room' where new_mapid = 490;
update dungeon set new_loc_name = 'Lastavard - Basement Passageway' where new_mapid = 491;
update dungeon set new_loc_name = 'Lastavard - Basement Control Room' where new_mapid = 493;
update dungeon set new_loc_name = 'Lastavard - Basement Battle Arena' where new_mapid = 495;
update dungeon set new_loc_name = 'Outer Area of Temple of Shadows' where new_mapid = 521;
update dungeon set new_loc_name = 'Lastavard - 4F Temple of Gran Kain / Kenya' where new_mapid = 530;
update dungeon set new_loc_name = 'Lastavard - 4F Viatas / Baromes / Endias' where new_mapid = 531;
update dungeon set new_loc_name = 'Lastavard - 4F Gardens / Edea' where new_mapid = 532;
update dungeon set new_loc_name = 'Lastavard - 4F Tiames / Ramias / Barode' where new_mapid = 533;
update dungeon set new_loc_name = 'Lastavard - 4F Cassandra / Dante' where new_mapid = 534;
update dungeon set new_loc_name = 'Lastavard - 3F Sanctuary of Oblivion' where new_mapid = 536;
update dungeon set new_loc_name = 'Grave of Ships - Outland' where new_mapid = 550;
update dungeon set new_loc_name = 'Grave of Ships - 1F-1' where new_mapid = 551;
update dungeon set new_loc_name = 'Grave of Ships - 1F-2' where new_mapid = 552;
update dungeon set new_loc_name = 'Grave of Ships - 1F-3' where new_mapid = 553;
update dungeon set new_loc_name = 'Grave of Ships - 2F-1' where new_mapid = 554;
update dungeon set new_loc_name = 'Grave of Ships - 2F-2' where new_mapid = 555;
update dungeon set new_loc_name = 'Grave of Ships - 2F-3' where new_mapid = 556;
update dungeon set new_loc_name = 'Grave of Ships - 3F' where new_mapid = 557;
update dungeon set new_loc_name = 'Grave of Ships - Deep Sea Floor' where new_mapid = 558;
update dungeon set new_loc_name = 'Cave of Desire - Outland' where new_mapid = 600;
update dungeon set new_loc_name = 'Cave of Desire - Lobby' where new_mapid = 601;
update dungeon set new_loc_name = 'Fallen Cave' where new_mapid = 778;
update dungeon set new_loc_name = 'Fallen Cave Underwater' where new_mapid = 779;
update dungeon set new_loc_name = '' where new_mapid = 780;
update dungeon set new_loc_name = '' where new_mapid = 781;
update dungeon set new_loc_name = '' where new_mapid = 1000;
update dungeon set new_loc_name = '' where new_mapid = 1001;
update dungeon set new_loc_name = '' where new_mapid = 1005;
update dungeon set new_loc_name = 'Ancient Space 1F' where new_mapid = 2000;
update dungeon set new_loc_name = 'Ancient Space 3F' where new_mapid = 2002;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 1' where new_mapid = 5068;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 2' where new_mapid = 5069;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 3' where new_mapid = 5070;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 4' where new_mapid = 5071;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 5' where new_mapid = 5072;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 6' where new_mapid = 5073;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 7' where new_mapid = 5074;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 8' where new_mapid = 5075;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 9' where new_mapid = 5076;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 10' where new_mapid = 5077;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 11' where new_mapid = 5078;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 12' where new_mapid = 5079;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 13' where new_mapid = 5080;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 14' where new_mapid = 5081;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 15' where new_mapid = 5082;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 16' where new_mapid = 5083;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 17' where new_mapid = 5084;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 18' where new_mapid = 5085;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 19' where new_mapid = 5086;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 20' where new_mapid = 5087;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 21' where new_mapid = 5088;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 22' where new_mapid = 5089;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 23' where new_mapid = 5090;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 24' where new_mapid = 5091;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 25' where new_mapid = 5092;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 26' where new_mapid = 5093;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 27' where new_mapid = 5094;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 28' where new_mapid = 5095;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 29' where new_mapid = 5096;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 30' where new_mapid = 5097;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 31' where new_mapid = 5098;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 32' where new_mapid = 5099;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 33' where new_mapid = 5100;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 34' where new_mapid = 5101;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 35' where new_mapid = 5102;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 36' where new_mapid = 5103;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 37' where new_mapid = 5104;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 38' where new_mapid = 5105;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 39' where new_mapid = 5106;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 40' where new_mapid = 5107;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 41' where new_mapid = 5108;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 42' where new_mapid = 5109;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 43' where new_mapid = 5110;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 44' where new_mapid = 5111;
update dungeon set new_loc_name = 'Giran Pledge Conference Hall 45' where new_mapid = 5112;
update dungeon set new_loc_name = 'Heine Underground House 1' where new_mapid = 5113;
update dungeon set new_loc_name = 'Heine Underground House 2' where new_mapid = 5114;
update dungeon set new_loc_name = 'Heine Underground House 3' where new_mapid = 5115;
update dungeon set new_loc_name = 'Heine Underground House 4' where new_mapid = 5116;
update dungeon set new_loc_name = 'Heine Underground House 5' where new_mapid = 5117;
update dungeon set new_loc_name = 'Heine Underground House 6' where new_mapid = 5118;
update dungeon set new_loc_name = 'Heine Underground House 7' where new_mapid = 5119;
update dungeon set new_loc_name = 'Heine Underground House 8' where new_mapid = 5120;
update dungeon set new_loc_name = 'Heine Underground House 9' where new_mapid = 5121;
update dungeon set new_loc_name = 'Heine Underground House 10' where new_mapid = 5122;
update dungeon set new_loc_name = 'Heine Underground House 11' where new_mapid = 5123;
update dungeon set new_loc_name = 'InnRoom - Talking Island' where new_mapid = 16384;
update dungeon set new_loc_name = 'Conference Hall - Talking Island' where new_mapid = 16896;
update dungeon set new_loc_name = 'InnRoom - Gludio' where new_mapid = 17408;
update dungeon set new_loc_name = 'Conference Hall - Gludio' where new_mapid = 17920;
update dungeon set new_loc_name = 'InnRoom - Giran' where new_mapid = 18432;
update dungeon set new_loc_name = 'Conference Hall - Giran' where new_mapid = 18944;
update dungeon set new_loc_name = 'InnRoom - Oren' where new_mapid = 19456;
update dungeon set new_loc_name = 'Conference Hall - Oren' where new_mapid = 19968;
update dungeon set new_loc_name = 'InnRoom - Windawood' where new_mapid = 20480;
update dungeon set new_loc_name = 'Conference Hall - Windawood' where new_mapid = 20992;
update dungeon set new_loc_name = 'InnRoom - Silver Knight Town' where new_mapid = 21504;
update dungeon set new_loc_name = 'Conference Hall - Silver Knight Town' where new_mapid = 22016;
update dungeon set new_loc_name = 'InnRoom - Heine' where new_mapid = 22528;
update dungeon set new_loc_name = 'Conference Hall - Heine' where new_mapid = 23040;
update dungeon set new_loc_name = 'InnRoom' where new_mapid = 23552;
update dungeon set new_loc_name = 'Conference Hall -' where new_mapid = 24064;
update dungeon set new_loc_name = 'InnRoom' where new_mapid = 24576;
update dungeon set new_loc_name = 'Conference Hall -' where new_mapid = 25088;
update dungeon set new_loc_name = 'InnRoom' where new_mapid = 20992;
update dungeon set new_loc_name = 'InnRoom' where new_mapid = 21504;
update dungeon set new_loc_name = 'InnRoom' where new_mapid = 22016;
update dungeon set new_loc_name = 'InnRoom' where new_mapid = 22528;
update dungeon set new_loc_name = 'InnRoom' where new_mapid = 23040;
update dungeon set new_loc_name = 'InnRoom' where new_mapid = 23552;
update dungeon set new_loc_name = 'InnRoom' where new_mapid = 24064;
update dungeon set new_loc_name = 'InnRoom' where new_mapid = 24576;
update dungeon set new_loc_name = 'InnRoom' where new_mapid = 25088;

# Update NPC name identifiers
update npc set name = 'Ghost - Red' where npcid = 46131;
update npc set note = 'Crystal Caverns' where npcid = 46131;
update npc set name = 'Ghost - Blue' where npcid = 46132;
update npc set note = 'Crystal Caverns' where npcid = 46132;

# update cleanup
update area set areaname = 'Gunter`s House' where areaid = 4 and mapid = 3;
update area set areaname = 'Hardin`s Laboratory' where areaid = 16 and mapid = 16;
update area set areaname = 'Nerupa`s Cave' where areaid = 17 and mapid = 17;
update area set areaname = 'Duplegenon`s Quarters' where areaid = 18 and mapid = 18;
update area set areaname = 'Pago`s Room' where areaid = 81 and mapid = 87;
update area set areaname = 'Jim`s Dungeon' where areaid = 216 and mapid = 237;
update area set areaname = '1F Evil Power King`s Office' where areaid = 300 and mapid = 453;
update area set areaname = '2F Evil Spirit King`s Office' where areaid = 307 and mapid = 462;
update area set areaname = '2F Evil Spirit King`s Library' where areaid = 308 and mapid = 463;
update area set areaname = '3F Bright Magic King`s Office' where areaid = 319 and mapid = 475;
update area set areaname = 'Assassin King`s Office' where areaid = 325 and mapid = 492;
update area set areaname = 'Pirate`s Isle' where areaid = 330 and mapid = 480;
update area set areaname = 'Kamyla`s Room' where areaid = 331 and mapid = 481;
update area set areaname = 'Franco`s Labyrinth' where areaid = 333 and mapid = 482;
update area set areaname = 'Doromond`s Room' where areaid = 342 and mapid = 8013;
update area set areaname = 'Count Taros` Throne Room' where areaid = 350 and mapid = 251;
update area set areaname = 'Barbados` Hideout' where areaid = 353 and mapid = 254;
update area set areaname = '4F Gran Kain`s Temple' where areaid = 360 and mapid = 530;
update area set areaname = '4F Barome`s Office' where areaid = 361 and mapid = 531;
update area set areaname = '4F Edea`s Office' where areaid = 362 and mapid = 532;
update area set areaname = '4F Barode`s Office' where areaid = 363 and mapid = 533;
update area set areaname = '4F Cassandra`s Office' where areaid = 364 and mapid = 534;
update area set areaname = 'Varlok`s Room' where areaid = 377 and mapid = 602;
update area set areaname = 'Varlok`s Lair' where areaid = 378 and mapid = 603;
update area set areaname = 'Yahee`s Laboratory' where areaid = 383 and mapid = 608;
update armor set name = 'Knight`s Hood' where item_id = 20005;
update armor set name = 'Knight`s Visor' where item_id = 20006;
update armor set name = 'Red Knight`s Hood' where item_id = 20027;
update armor set name = 'Soverign`s Majesty' where item_id = 20051;
update armor set name = 'Varlok`s Blood-Colored Cloak' where item_id = 20062;
update armor set name = 'Tarak`s Cloak' where item_id = 20076;
update armor set name = 'Tarak`s Robe' where item_id = 20152;
update armor set name = 'Tarak`s Gloves' where item_id = 20186;
update armor set name = 'Tarak`s Boots' where item_id = 20216;
update armor set name = 'Dark Elf`s Training Helmet' where item_id = 20388;
update armor set name = 'Dark Elf`s Training Cloak' where item_id = 20400;
update armor set name = 'Dark Elf`s Training Boots' where item_id = 20405;
update armor set name = 'Red Orc`s Mask' where item_id = 20458;
update armor set name = 'Red Orc`s Earrings' where item_id = 20459;
update armor set name = 'T-shirt with %i\'s Strength' where item_id = 21028;
update armor set name = 'T-shirt with %i\'s Agility' where item_id = 21029;
update armor set name = 'T-shirt with %i\'s Charm' where item_id = 21030;
update armor set name = 'T-shirt with %i\'s Magic Power' where item_id = 21031;
update armor set name = 'T-shirt with %i\'s Physical Strength' where item_id = 21032;
update armor set name = 'T-shirt with %i\'s Mana' where item_id = 21033;
update armor set name = 'Swimwear Men`s Briefs' where item_id = 21063;
update armor set name = 'Swimwear Men`s Trunks' where item_id = 21064;
update armor set name = 'Swimwear Female`s One Piece' where item_id = 21065;
update armor set name = 'Swimwear Female`s Bikini' where item_id = 21066;
update armor set unidentified_name_id = 'Swimwear Men`s Briefs' where item_id = 21063;
update armor set unidentified_name_id = 'Swimwear Men`s Trunks' where item_id = 21064;
update armor set unidentified_name_id = 'Swimwear Female`s One Piece' where item_id = 21065;
update armor set unidentified_name_id = 'Swimwear Female`s Bikini' where item_id = 21066;
update armor set identified_name_id = 'Swimwear Men`s Briefs' where item_id = 21063;
update armor set identified_name_id = 'Swimwear Men`s Trunks' where item_id = 21064;
update armor set identified_name_id = 'Swimwear Female`s One Piece' where item_id = 21065;
update armor set identified_name_id = 'Swimwear Female`s Bikini' where item_id = 21066;
update armor set name = 'Ice Queen`s Earring Lvl 0' where item_id = 21081;
update armor set name = 'Ice Queen`s Earring Lvl 1' where item_id = 21082;
update armor set name = 'Ice Queen`s Earring Lvl 2' where item_id = 21083;
update armor set name = 'Ice Queen`s Earring Lvl 3' where item_id = 21084;
update armor set name = 'Ice Queen`s Earring Lvl 4' where item_id = 21085;
update armor set name = 'Ice Queen`s Earring Lvl 5' where item_id = 21086;
update armor set name = 'Ice Queen`s Earring Lvl 6' where item_id = 21087;
update armor set name = 'Ice Queen`s Earring Lvl 7' where item_id = 21088;
update armor set name = 'Ice Queen`s Earring Lvl 8' where item_id = 21089;
update armor set name = 'Ice Queen`s Earring Lvl 9' where item_id = 21090;
update armor set name = 'Ice Queen`s Earring Lvl 10' where item_id = 21091;
update armor set name = 'T-shirt with %i`s Mana' where item_id = 21108;
update armor set name = 'Mermaid`s Ring' where item_id = 30006;
update armor set unidentified_name_id = 'Mermaid`s Ring' where item_id = 30006;
update armor set identified_name_id = 'Mermaid`s Ring' where item_id = 30006;
update droplist set mob_name = 'Betrayer`s Skeleton Guardsman' where mobid = 45100;
update droplist set item_name = 'Wizard`s Staff' where itemId = 129;
update droplist set item_name = 'Native`s Totem' where itemId = 140329;
update droplist set item_name = 'Native`s Totem' where itemId = 40329;
update droplist set item_name = 'Black Knight`s Pledge Document' where itemId = 40608;
update droplist set item_name = 'Arachnevil Elder`s Claw' where itemId = 40590;
update droplist set item_name = 'Resta`s Ring' where itemId = 40631;
update droplist set item_name = 'Apparition`s Bag' where itemId = 40548;
update droplist set item_name = 'Guardian`s Bag' where itemId = 40528;
update droplist set item_name = 'Basilisk`s Horn' where itemId = 40646;
update droplist set item_name = 'Diego`s Old Diary' where itemId = 40630;
update droplist set item_name = 'Assassin Master`s Box' where itemId = 40571;
update droplist set item_name = 'Ancients` Book of Magic, Volume 1' where itemId = 40420;
update droplist set item_name = 'Ancients` Book of Magic, Volume 2' where itemId = 40421;
update droplist set item_name = 'Ancients` Book of Magic, Volume 3' where itemId = 40422;
update droplist set item_name = 'Ancients` Book of Magic, Volume 4' where itemId = 40423;
update droplist set item_name = 'Drake`s Claw' where itemId = 40622;
update droplist set item_name = 'Kalba`s Scroll' where itemId = 140130;
update droplist set item_name = 'Gian`s Scroll' where itemId = 140129;
update droplist set item_name = 'Kalba`s Scroll' where itemId = 40130;
update droplist set item_name = 'Gian`s Scroll' where itemId = 40129;
update droplist set item_name = 'Devil`s Red Shackles' where itemId = 40462;
update droplist set item_name = 'Devil`s White Shackles' where itemId = 40464;
update droplist set item_name = 'Devil`s Blue Shackles' where itemId = 40463;
update droplist set item_name = 'Devil`s Black Shackles' where itemId = 40461;
update droplist set item_name = 'Tarak`s Tooth' where itemId = 40481;
update droplist set item_name = 'Tarak`s Devil Book, Volume 1' where itemId = 40477;
update droplist set item_name = 'Tarak`s Devil Book, Volume 2' where itemId = 40478;
update droplist set item_name = 'Tarak`s Devil Book, Volume 3' where itemId = 40479;
update droplist set item_name = 'Tarak`s Devil Book, Volume 4' where itemId = 40480;
update droplist set item_name = 'Tarak`s Sickle' where itemId = 40473;
update droplist set item_name = 'Tarak`s Head' where itemId = 40475;
update droplist set item_name = 'Tarak`s Hand' where itemId = 40476;
update droplist set item_name = 'Tarak`s Poison' where itemId = 40474;
update droplist set item_name = 'Tarak`s Tongue' where itemId = 40482;
update droplist set item_name = 'Devil`s Blood' where itemId = 40031;
update droplist set item_name = 'Devil`s Blood' where itemId = 45164;
update droplist set item_name = 'Ramia`s Scale' where itemId = 40544;
update droplist set item_name = 'Thor`s Hammer' where itemId = 450000;
update droplist set item_name = 'Eva`s Scorn' where itemId = 36;
update droplist set item_name = 'Friend`s Bag' where itemId = 40710;
update droplist set item_name = 'Attendant`s Scripture' where itemId = 40968;
update etcitem set name = 'Devil`s Blood' where item_Id = 40031;
update etcitem set name = 'Gian`s Scroll' where item_Id = 40129;
update etcitem set name = 'Kalba`s Scroll' where item_Id = 40130;
update etcitem set name = 'Boat Ticket to Pirate Island' where item_Id = 40302;
update etcitem set name = 'Native`s Totem' where item_Id = 40031;
update etcitem set name = 'Kalba`s Scroll' where item_Id = 140130;
update etcitem set name = 'Alchemist`s Stone' where item_Id = 40414;
update etcitem set name = 'Tarak`s Valuables' where item_Id = 40418;
update etcitem set name = 'Ancients` Book of Magic, Volume 1' where item_Id = 40420;
update etcitem set name = 'Ancients` Book of Magic, Volume 2' where item_id = 40421;
update etcitem set name = 'Ancients` Book of Magic, Volume 3' where item_Id = 40422;
update etcitem set name = 'Ancients` Book of Magic, Volume 4' where item_Id = 40423;
update etcitem set name = 'Devil`s Red Shackles' where item_Id = 40462;
update etcitem set name = 'Devil`s White Shackles' where item_Id = 40464;
update etcitem set name = 'Devil`s Blue Shackles' where item_Id = 40463;
update etcitem set name = 'Devil`s Black Shackles' where item_Id = 40461;
update etcitem set name = 'Tarak`s Sickle' where item_Id = 40473;
update etcitem set name = 'Tarak`s Poison' where item_Id = 40474;
update etcitem set name = 'Tarak`s Head' where item_Id = 40475;
update etcitem set name = 'Tarak`s Hand' where item_Id = 40476;
update etcitem set name = 'Tarak`s Devil Book, Volume 1' where item_Id = 40477;
update etcitem set name = 'Tarak`s Devil Book, Volume 2' where item_Id = 40478;
update etcitem set name = 'Tarak`s Devil Book, Volume 3' where item_Id = 40479;
update etcitem set name = 'Tarak`s Devil Book, Volume 4' where item_Id = 40480;
update etcitem set name = 'Tarak`s Tooth' where item_Id = 40481;
update etcitem set name = 'Tarak`s Tongue' where item_Id = 40482;
update etcitem set name = 'Pan`s Mane' where item_Id = 40519;
update etcitem set name = 'Guardian`s Bag' where item_Id = 40528;
update etcitem set name = 'Key to Ramia`s Room' where item_Id = 40543;
update etcitem set name = 'Ramia`s Scale' where item_Id = 40544;
update etcitem set name = 'Ronde`s Pouch' where item_Id = 40545;
update etcitem set name = 'Marshall`s Reward' where item_Id = 40546;
update etcitem set name = 'Apparition`s Bag' where item_Id = 40548;
update etcitem set name = 'Bludika`s Pouch' where item_Id = 40553;
update etcitem set name = 'Aria`s Reward' where item_Id = 40570;
update etcitem set name = 'Assassin Master`s Box' where item_Id = 40571;
update etcitem set name = 'Assassin`s Token' where item_Id = 40572;
update etcitem set name = 'Arachnevil Elder`s Claw' where item_Id = 40590;
update etcitem set name = 'Piece of Scout`s Report' where item_Id = 40593;
update etcitem set name = 'Overseer`s Document' where item_Id = 40595;
update etcitem set name = 'Torn Scout`s Report' where item_Id = 40597;
update etcitem set name = 'Kan`s Pouch' where item_Id = 40598;
update etcitem set name = 'Black Knight`s Pledge Document' where item_Id = 40608;
update etcitem set name = 'Drake`s Claw' where item_Id = 40622;
update etcitem set name = 'Diego`s Old Diary' where item_Id = 40630;
update etcitem set name = 'Resta`s Ring' where item_Id = 40631;
update etcitem set name = 'Basilisk`s Horn' where item_Id = 40646;
update etcitem set name = 'Assassin`s Rusted Sword' where item_Id = 40648;
update etcitem set name = 'Friend`s Bag' where item_Id = 40710;
update etcitem set name = 'Grandfather`s Treasure' where item_Id = 40716;
update etcitem set name = 'Lastavard`s Secret Weapon Production Method' where item_Id = 40965;
update etcitem set name = 'Fidelity`s Secret Armor Production Method' where item_Id = 40966;
update etcitem set name = 'Attendant`s Scripture' where item_Id = 40968;
update etcitem set name = 'Roy`s Pouch' where item_Id = 41003;
update etcitem set name = 'Rabla`s Pouch' where item_Id = 41004;
update etcitem set name = 'Rabor`s Pouch' where item_Id = 41006;
update etcitem set name = 'Scroll of Teleportation - Giant`s Grave' where item_Id = 42021;
update etcitem set unidentified_name_id = '$230 - Giant`s Grave' where item_Id = 42021;
update etcitem set identified_name_id = '$230 - Giant`s Grave' where item_Id = 42021;
update etcitem set name = 'Gian`s Scroll' where item_Id = 140129;
update etcitem set name = 'Kalba`s Scroll' where item_Id = 140130;
update etcitem set name = 'Native`s Totem' where item_Id = 140329;
update etcitem set name = 'Larson`s Recommendation Letter' where item_Id = 41317;
update etcitem set name = 'Kuen`s Note' where item_Id = 41318;
update etcitem set name = 'Parum`s Crop Pouch' where item_Id = 41355;
update etcitem set name = 'Parum`s Volunteer List' where item_Id = 41356;
update etcitem set name = 'Hero`s Mark' where item_Id = 41402;
update etcitem set name = 'Kuzak`s Food' where item_Id = 41403;
update etcitem set name = 'Kuzak`s Wonder Drug' where item_Id = 41404;
update etcitem set name = 'Scroll of Teleportation - Count`s Room' where item_Id = 42059;
update etcitem set unidentified_name_id = '$230 - Count`s Room' where item_Id = 42059;
update etcitem set identified_name_id = '$230 - Count`s Room' where item_Id = 42059;
update etcitem set name = 'Ice Demon`s Pouch' where item_Id = 49032;
update etcitem set name = 'Ice Queen`s Pouch' where item_Id = 49033;
update etcitem set name = 'Ice Queen`s Box' where item_Id = 49034;
update etcitem set name = 'Sharna`s Transformation Scroll (Level 30)' where item_Id = 49149;
update etcitem set name = 'Sharna`s Transformation Scroll (Level 40)' where item_Id = 49150;
update etcitem set name = 'Sharna`s Transformation Scroll (Level 52)' where item_Id = 49151;
update etcitem set name = 'Sharna`s Transformation Scroll (Level 55)' where item_Id = 49152;
update etcitem set name = 'Sharna`s Transformation Scroll (Level 60)' where item_Id = 49153;
update etcitem set name = 'Sharna`s Transformation Scroll (Level 65)' where item_Id = 49154;
update etcitem set name = 'Sharna`s Transformation Scroll (Level 70)' where item_Id = 49155;
update etcitem set name = 'Dantes` Royal Letter' where item_Id = 49160;
update etcitem set name = 'Spirit`s Whisper' where item_Id = 49161;
update etcitem set name = 'Ancient Dar Elf`s Secret Text' where item_Id = 49162;
update etcitem set name = 'Ma`s Horn Flute' where item_Id = 49167;
update etcitem set name = 'Sleyin`s Order' where item_Id = 49171;
update etcitem set name = 'Sleyin`s First Letter' where item_Id = 49172;
update etcitem set name = 'Sleyin`s Second Letter' where item_Id = 49173;
update etcitem set name = 'Sleyin`s Third Letter' where item_Id = 49174;
update etcitem set name = 'Sleyin`s Fourth Letter' where item_Id = 49175;
update etcitem set name = 'Sleyin`s Fifth Letter' where item_Id = 49176;
update etcitem set name = 'Sleyin`s Sixth Letter' where item_Id = 49177;
update etcitem set name = 'Sleyin`s Amulet' where item_Id = 49178;
update etcitem set name = 'Sleyin`s Pouch' where item_Id = 49179;
update etcitem set name = 'Sleyin`s Pouch' where item_Id = 49180;
update etcitem set name = 'Prochel`s Letter' where item_Id = 49209;
update etcitem set name = 'Prochel`s First Note' where item_Id = 49213;
update etcitem set name = 'Prochel`s Second Note' where item_Id = 49214;
update etcitem set name = 'Prochel`s Mineral Pouch' where item_Id = 49215;
update etcitem set name = 'Prochel`s Amulet' where item_Id = 49216;
update etcitem set name = 'Orc Emissary`s Scroll of Polymorph' where item_Id = 49220;
update etcitem set name = 'Kurtz`s Secret' where item_Id = 49235;
update etcitem set name = 'Island Drake`s Crystal' where item_Id = 49237;
update etcitem set name = 'Resta`s Ring' where item_Id = 49277;
update etcitem set name = 'Bag of Devil`s Blood' where item_Id = 90004;
update etcitem set unidentified_name_id = 'Bag of Devil`s Blood' where item_Id = 90004;
update etcitem set identified_name_id = 'Bag of Devil`s Blood' where item_Id = 90004;
update getback set note = 'Gunter`s Cave' where area_mapid = 3;
update getback set note = 'Hardin`s Lab' where area_mapid = 16;
update getback set note = 'Nerupa`s Cave' where area_mapid = 17;
update getback set note = 'Pago`s Room' where area_mapid = 87;
update getback set note = 'Helper`s Room' where area_mapid = 99;
update getback set note = 'Pirate`s Isle' where area_mapid = 480;
update getback set note = 'Kamyla`s Room' where area_mapid = 481;
update getback set note = 'Grave of Ships Outland' where area_mapid = 550;
update getback set note = 'Grave of Ships 1F-1' where area_mapid = 551;
update getback set note = 'Grave of Ships 1F-2' where area_mapid = 552;
update getback set note = 'Grave of Ships 1F-3' where area_mapid = 553;
update getback set note = 'Grave of Ships 2F-1' where area_mapid = 554;
update getback set note = 'Grave of Ships 2F-2' where area_mapid = 555;
update getback set note = 'Grave of Ships 2F-3' where area_mapid = 556;
update getback set note = 'Grave of Ships 3F' where area_mapid = 557;
update getback set note = 'Deep Sea Floor' where area_mapid = 558;
update getback set note = 'IGG Castle 1F - Dwarf Mine' where area_mapid = 255;
update getback set note = 'IGG Castle 2F - Wilderness' where area_mapid = 256;
update getback set note = 'Gludin Traders Village' where area_mapid = 340;
update getback set note = 'IGG Castle 2F - Wilderness' where area_mapid = 256;
update getback set note = 'Singing Islands' where area_mapid = 8011;
update getback set note = 'Singing Island West' where area_mapid = 8012;
update getback set note = 'Doromond`s Room' where area_mapid = 8013;
update getback set note = 'Training Room' where area_mapid = 8014;
update getback set note = 'Singing Island North' where area_mapid = 8015;
update getback set note = 'Franco`s Labyrinth' where area_mapid = 482;
update getback set note = 'Closed Jail of Diego' where area_mapid = 483;
update getback set note = 'Underground Jail of Jose' where area_mapid = 484;

-- added info for Illusionist quests 15,30
update droplist set chance = 50000 where mobid = 45152 and itemid = 40510;
update droplist set chance = 50000 where mobid = 45152 and itemid = 40511;
update droplist set chance = 50000 where mobid = 45152 and itemid = 40512;

insert into droplist values
(46163,'Vengeful Spirit of Elmore Commander',49190,'Sealed Article of Solsheica',1,1,1000000), 
(45117,'Contaminated Orc',49169,'Contaminated Breath of Orcs',1,1,100000),
(45118,'Contaminated Orc Archer',49169,'Contaminated Breath of Orcs',1,1,100000),
(45128,'Contaminated Orc Warrior',49169,'Contaminated Breath of Orcs',1,1,100000),
(45153,'Contaminated Fairy',49170,'Contaminated Nucleus of Spirit',1,1,75000),
(46162,'Elmore Zombie Commander',40013,'Haste Potion',1,2,90000),
(46162,'Elmore Zombie Commander',40014,'Potion of Bravery',1,2,90000),
(46162,'Elmore Zombie Commander',49187,'Breath of Elmore Zombie Commander',1,1,1000000);

insert into spawnlist values
(400004,'Elmore Zombie Commander',1,46162,0,34144,32276,10,10,0,0,0,0,5,240,420,4,0,100,0,0);

update etcitem set use_type = 'normal' where item_id = 49189;
update etcitem set use_type = 'normal' where item_id = 49188;
update etcitem set stackable = '1' where item_id = 49169;

-- added Joe's Stone Golem a weapon crafter
insert into spawnlist_npc values (90452,'Joe`s Stone Golem',1,71252,33712,32494,0,0,4,0,4,0);
update weapon set name = 'Dagger of Magic Power' where item_id = 259;
update weapon set name = 'Arch Mage`s Staff' where item_id = 261;
update weapon set name = 'Spear of Intense Winter' where item_id = 263;
update weapon set name = 'Thunder God`s Sword' where item_id = 264;

-- update missing or incorrect mapids
UPDATE mapids set locationname = 'Hardin`s Laboratory' WHERE mapid = 16
UPDATE mapids set locationname = 'Gerard`s Test Dungeon' WHERE mapid = 22
UPDATE mapids set locationname = 'Thebes Desert' WHERE mapid = 780
UPDATE mapids set locationname = 'Thebes Pyramid Inside' WHERE mapid = 781
UPDATE mapids set locationname = 'Thebes Osiris Altar' WHERE mapid = 782

# Remove old Crystal Caverns Dungeon Data
DELETE FROM dungeon WHERE src_mapid = 72;
DELETE FROM dungeon WHERE src_mapid = 73;
DELETE FROM dungeon WHERE src_mapid = 74;
DELETE FROM dungeon WHERE new_mapid = 72;
DELETE FROM dungeon WHERE new_mapid = 73;
DELETE FROM dungeon WHERE new_mapid = 74;

# Add Updated Crystal Caves Dungeon Data
INSERT INTO `dungeon` VALUES
(32872,32835,72,'Crystal Caverns 1F',32782,32735,73,'Crystal Caverns 2F',2),
(32872,32834,72,'Crystal Caverns 1F',32782,32735,73,'Crystal Caverns 2F',2),
(32781,32735,73,'Crystal Caverns 2F',32871,32834,72,'Crystal Caverns 1F',6),
(32781,32736,73,'Crystal Caverns 2F',32871,32834,72,'Crystal Caverns 1F',6),
(32753,32739,73,'Crystal Caverns 2F',32728,32816,74,'Crystal Caverns 3F',0),
(32754,32739,73,'Crystal Caverns 2F',32728,32816,74,'Crystal Caverns 3F',0),
(32728,32817,74,'Crystal Caverns 3F',32754,32740,73,'Crystal Caverns 2F',4),
(32728,32816,74,'Crystal Caverns 3F',32754,32740,73,'Crystal Caverns 2F',0);